[미키] 자바스크립트에서의 Inversion of Control
woowacourse/tecoble pull request #325
Opened 2021-05-14 16:46 UTC by 0307kwon

초안 작성하여 올리겠습니다! 😁🔥🔥

2021-05-15 03:26 UTC, GwangYeol-Im requested changes
초안 글 잘 읽었습니다. 미키의 스타일이 녹아 있는 글이라 더 쉽게 읽힌 것 같네요 ;) 개인적으로 의견을 첨부하자면, IoC나 DI같은 해당 용어를 한 번 쯤은 한글 + 영어로 병기해보면 어떨까요? 해당 단어에 대한 명시적인 표현이 없는 것 같아 글의 맥락에 기대어 단어의 뜻을 유추하게 되는 것 같았어요! 그 부분말고는 전체적으로 매끄러운 글이었다고 생각합니다👏🏻

2021-05-15 03:26 UTC, GwangYeol-Im commented on src/content/post/2021-05-14-inversion-of-control.md
> +손님이 택시 기사에게 명령하던 것이 택시 기사가 손님에게 도착함을 알리는 방식으로 제어가 역전된 것이다.
현실 세계의 비유를 들어서 설명하니 더 와닿네요 :)

2021-05-15 03:26 UTC, GwangYeol-Im commented on src/content/post/2021-05-14-inversion-of-control.md
> +도구를 사용하는 이유에 대한 내제화가 될 수 있도록 노력해야겠다. 🔥
`내제화` 오타 있어요!

2021-05-15 03:26 UTC, GwangYeol-Im commented on src/content/post/2021-05-14-inversion-of-control.md
> +## 🔍 javascript에서의 IoC
대주제를 javascript 로 잡았다는 것은 Redux 와 React가 js의 하위 개념이라고 생각하기 때문일까요? 👀

2021-05-15 03:27 UTC, 0imbean0 approved these changes
글 잘 읽었습니다. 😀  미키의 블로그가 유명한 이유가 있었군요. 👍

사소한 코멘트 하나 남겼습니다. 그외에는 전체적으로 정말 잘 쓰셨네요. Approve 하겠습니다.

+ 추가) 개인적인 의견 하나만 드리면, 아직 잘 모르는 개념(컴파일 타임, 런타임)이 전제가 되었는데, 아직 저희 블로그에 관련 내용의 포스팅이 없더라구요. 다음 주제로 써주시면 어떨까요?

2021-05-15 03:30 UTC, 0imbean0 commented on src/content/post/2021-05-14-inversion-of-control.md
> +## 🔍 javascript에서의 IoC
나도 여기에 같은 모멘트 남겼는데 어디갔지? 🤔

2021-06-12 07:57 UTC, 0307kwon reviewed
@0imbean0 @GwangYeol-Im 피드백 감사합니다!! ㅎㅎ
피드백 토대로 수정해봤어용 😁 확인해주시공 approve 부탁드립니다! :)

2021-06-12 07:57 UTC, 0307kwon commented on src/content/post/2021-05-14-inversion-of-control.md
> +## 🔍 javascript에서의 IoC
조금 react에 초점이 맞춰져 설명이 되어있는듯 합니다!
그래서 `react에서의 IoC`라는 표현을 사용해볼까...? 생각해보았지만
제가 전달하고 싶은 것은 프론트엔드에서 IoC가 어떻게 적용되는가의 예시였기 때문에
javascript에서 라는 표현을 프론트 엔드로 수정해보았습니다! 😊

2021-06-13 10:40 UTC, GwangYeol-Im approved these changes

2021-06-16 04:37 UTC, devJang requested changes
미키 잘 읽었습니다.
리뷰가 늦은 이유에 대해 변명을 해보자면
작성해주신 글을 읽고 혼란스러워 몇번을 또 읽고 IoC에 대해 다시 한번 학습하고 왔답니다.

개인적으로는 미키가 작성해주신 글에 동의하지 않습니다.
리액트를 사용하면서 IoC를 떠올린 게 아니라 디자인 패턴에 억지로 프론트엔드 개발 트렌드를 끼워 맞추는게 아닐까 생각이 들었습니다.

물론 디자인 패턴을 공부하고 학습하는 것은 좋고
IoC를 소개하는 부분까지는 너무나 흥미롭게 읽었습니다.

하지만 **IoC를 적용하는 이유**와 리액트 & 리덕스에서의 IoC패턴은 과연? 그럴까? 라는 생각에 의문이 많이 듭니다.

### React

`View`를 관리해주는 선언형 라이브러리입니다.
리액트의 관심사는 상태를 렌더링하는 것이거든요.
(물론 리액트가 헤비해지면서 애매하게 보이는 측면이 있습니다)

### Redux

Flux 구조기반의 예측 가능한 상태 컨테이너입니다.

---

코드 설명도 인스턴스를 다루는 것이라 더욱 헷갈리는 것 같습니다.
혹시나 IoC에서 `제어의 역전`만을 보고 프론트엔드에 대입하신걸까요?

결론적으로
`IoC`는 `Bean`... 즉 생성자, 인스턴스 등.. 객체의 의존성을 관리하는 원칙으로 생각하는데
이게 프론트엔드와 어느 공통점이 있을까 혼란스러움을 느꼈고 글 어디를 봐도 공감대를 느낄 수 없었습니다.

차라리 `Angular`, `NestJS` 등을 예로 들었다면 조금은 납득이 되지 않았을까 싶어요

리액트에서 의존성 주입을 하는 예인데요. 
https://www.youtube.com/watch?v=1o1CqzTtt2o

위의 코드들을 보고도 `IoC`가 떠오르실지 궁금합니다.

미키 덕분에 IoC의 구현 원칙에 대해 흥미롭게 읽고 다시 한번 학습해봤습니다.
하지만 자신이 생각하는 고민을 느낄 수가 없어 아쉽네요

2021-06-16 04:37 UTC, devJang commented on src/content/post/2021-05-14-inversion-of-control.md
> +[React 이름의 유래](https://www.freecodecamp.org/news/yes-react-is-taking-over-front-end-development-the-question-is-why-40837af8ab76/)
리스트 형태에 맞게 제공합시다~

2021-06-16 04:37 UTC, devJang commented on src/content/post/2021-05-14-inversion-of-control.md
> +### 👎 DI가 적용되지 않은 경우
예시 코드는 그저 `인스턴스`를 다루는 예인데요
내용은 `React`, `Redux`로 되어있어 혼란스럽습니다.

`React` 프로젝트 진행을 통해 `IoC`가 떠올랐다면 그 부분을 코드로 풀어주실 수 있을까요?

2021-06-16 06:16 UTC, wannte reviewed
`프론트엔드에서의 IoC`라는 제목 좋은 것 같아요! (백엔드에서 하루종일 나오는 개념인데, 프론트에서는 요런식으로 사용한다! 패기있는 느낌)

IoC의 개념의 설명도 중요하지만, `프론트엔드의` 요 부분을 조금더 중점적으로 다뤄도 좋은 글이 될 것 같아요!

2021-06-16 06:16 UTC, wannte commented on src/content/post/2021-05-14-inversion-of-control.md
> +## 😵 Dependency Injection
DI의 개념에 대한 정의를 한문장으로 작성해주면 좋을 것 같아요!

IoC와 오해하는 개념이다 ->  IoC를 구현하는 한 가지 방법이다 -> 코드로 확인해보자 (그렇다면 DI는 뭐지? 이런 의문이 남을 것 같아요!)

누가 DI 관련해서 글 썼었더라고요.. 호호호 
[DI 관련 글](https://woowacourse.github.io/javable/post/2021-04-27-dependency-injection/)

2021-06-16 06:16 UTC, wannte commented on src/content/post/2021-05-14-inversion-of-control.md
> +### 👎 DI가 적용되지 않은 경우
비슷한 생각인데요! 제목이 `프론트엔드에서의 IoC`인데, 지금의 예시는 DI를 이용, 이용하지 않은 IoC의 간단한 예시만을 보여주고 있네요!

프론트에든에서의 IoC는 어떤 식으로 사용되는 지 궁금해요!

2021-06-17 07:39 UTC, da-nyee commented on src/content/post/2021-05-14-inversion-of-control.md
> +## 🎁 Inversion of Control 이란?
저도 이 부분 동의합니다! 할리우드 예제는 크게 와닿지 않았던 거 같아요...!
서론 길이를 조금 줄여도 괜찮을 거 같습니다 !

2021-06-17 08:06 UTC, da-nyee reviewed
안녕하세요, 미키!
백엔드 크루 다니입니다 🙌

이번 주제 정말 흥미로웠어요!
글 잘 읽었습니다 👍

코멘트 몇 개 남겼는데, 참고해주시면 감사하겠습니다 ~!

2021-06-17 08:06 UTC, da-nyee commented on src/content/post/2021-05-14-inversion-of-control.md
> +하지만 DI는 제어의 역전을 구현하기 위한 한 가지 방법일 뿐이다.
```suggestion
하지만 DI는 제어의 역전을 달성하기 위한 한 가지 방법일 뿐이다.
```

이 문장이 조금 어색하다고 느껴지는데요...!
제안처럼 변경해보는 건 어떨까요??

2021-07-03 07:18 UTC, 0307kwon commented on src/content/post/2021-05-14-inversion-of-control.md
> +date: '2020-05-15T12:00:00.000Z'
앗 날짜가 또 ㅠㅜ 수정하였습니다! 👍👍

2021-07-03 07:21 UTC, 0307kwon commented on src/content/post/2021-05-14-inversion-of-control.md
> +[React 이름의 유래](https://www.freecodecamp.org/news/yes-react-is-taking-over-front-end-development-the-question-is-why-40837af8ab76/)
수정하였습니다~

2021-07-03 07:23 UTC, 0307kwon commented on src/content/post/2021-05-14-inversion-of-control.md
> +### 👎 DI가 적용되지 않은 경우
두 분다 피드백 감사합니다! 👍👍 DI라는 용어가 spring에서의 IoC의 개념과 혼동될 수 있는 여기 있을 것 같아
DI 부분을 삭제하고 프론트엔드에서 IoC를 적용한다면 어떤 코드일지 간단하게 작성해보았습니다!

2021-07-03 07:32 UTC, 0307kwon commented on src/content/post/2021-05-14-inversion-of-control.md
> +## 🎁 Inversion of Control 이란?
다시보니 확실히 두가지 예시가 언급되고 있어 글이 혼란스러운 면이 있네요!
두 분다 감사합니다!! 👍👍

2021-07-03 07:38 UTC, 0307kwon commented on src/content/post/2021-05-14-inversion-of-control.md
> +## 😵 Dependency Injection
DI에 대해서 고민을 많이 해보았는데요. DI가 spring에서 IoC와 함께 많이 언급되는 것 같더라구용
제가 소개하는 것은 `제어의 역전`이라는 전반적인 개념 정도인데 spring의 IoC나 DI로 독자들이 혼동할 수도 있을 것 같고
예시를 들어보려해도 제가 쓰려는 글의 논점에서 벗어나는 것 같아 DI 부분은 삭제해보았습니다.
의견 감사합니다 완태! ㅎㅎ

2021-07-03 07:40 UTC, 0307kwon commented on src/content/post/2021-05-14-inversion-of-control.md
> +}
코드를 전반적으로 수정해보았습니다! 고마워요 다니~ 👍👍👍

2021-07-03 07:41 UTC, 0307kwon commented on src/content/post/2021-05-14-inversion-of-control.md
> +하지만 DI는 제어의 역전을 구현하기 위한 한 가지 방법일 뿐이다.
수정하다보니 DI부분이 아예 삭제되었네용 😂
의견 감사합니다 다니! 👍👍

2021-07-03 08:36 UTC, devJang approved these changes

2021-07-03 08:36 UTC, merged