[심바] DOM(Document Object Model) Element 다루기
woowacourse/tecoble pull request #330
Opened 2021-05-17 01:01 UTC by 0imbean0

@jho2301 @0307kwon 
초안 작성하여 리뷰 요청합니다

2021-05-19 04:36 UTC, jho2301 commented
안녕하세요 심바~

로컬개발서버에서 아티클페이지로 접근이 안되는데 확인 한 번 부탁드려도 될까요?

2021-05-19 04:48 UTC, jho2301 requested changes

2021-05-19 04:48 UTC, jho2301 commented on src/content/post/2021-05-09-handle-dom-element.md
> +`document.createElement` 를 사용하여 elem 생성할 수 있다. 이때 인자로 태그를 넘겨주면 원하는 태그의 elem 생성할 수 있다.
`태그`보다는 `태그이름`이 더 명시적일 것 같습니다~

2021-05-19 04:48 UTC, jho2301 commented on src/content/post/2021-05-09-handle-dom-element.md
> +이때 반환된 elem 들은 유사배열로 반환되며, Array는 아니지만 `forEach` 를 사용할 수 있다.
터미널이나 크롬 콘솔탭을 이용해 인스턴스의 이름과 프로퍼티들을 직접 보여주면 어떨까요?  제안해봅니다!

2021-05-19 04:48 UTC, jho2301 commented on src/content/post/2021-05-09-handle-dom-element.md
> +`innerHTML` 을 사용하여 DOM을 다룰 때는 빈 문자열을 사용하여 elem를 삭제하기도 하였다.
여기서 글의 흐름이 끊기는 것 같습니다!
독자가 innerHTML을 사용해보지 않은 경우가 있을 수 있기에 innerHTML을 이용한 DOM요소 제거 방법을 소개하는 식으로 변경하면 어떨까요?

2021-05-20 07:58 UTC, 0307kwon approved these changes
전반적으로 깔끔하게 쓰인 글이라 피드백 하나만 드리고 Approve하겠습니다! 👍👍
고생하셨습니다 🎉🎉

2021-05-20 07:58 UTC, 0307kwon commented on src/content/post/2021-05-09-handle-dom-element.md
> +지난 글에서는 innerHTML의 위험성, **XSS**에 대해 알아보았다.
독자가 지난 글을 읽었다는 가정 하에 내용이 진행되고 있는데   
왜 innerHTML을 사용하지 않고 element를 사용하면 더 안전한지 살짝 언급해보면 어떨까요? 😁

2021-06-16 08:56 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +이때 반환된 elem 들은 유사배열로 반환되며, Array는 아니지만 `forEach` 를 사용할 수 있다.
좋은 생각인 것 같아서 글을 전체적으로 수정해봤어요 !!

2021-06-16 08:57 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +지난 글에서는 innerHTML의 위험성, **XSS**에 대해 알아보았다.
다시 생각해보니 문맥이 단절된 느낌이 있었던 것 같아요. 👍

2021-06-16 09:05 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +`innerHTML` 을 사용하여 DOM을 다룰 때는 빈 문자열을 사용하여 elem를 삭제하기도 하였다.
다른 예시들을 추가하면서, 이 부분은 글이랑 혼자 동떨어진 것 같아서 삭제했습니다. 🙂

2021-06-16 11:20 UTC, jho2301 commented
반영된 것 확인했습니다. 고생하셨습니다~!

2021-06-16 11:22 UTC, jho2301 approved these changes
반영된 것 확인했습니다! 고생하셨습니다~!

2021-06-16 12:19 UTC, devJang requested changes
이번 글에는 아쉬운 부분이 좀 많네요
코멘트를 모두 남겼으니 하나하나 다 확인부탁드립니다!

2021-06-16 12:19 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +이때 반환된 elem 들은 NodeList로 반환되며, Array는 아니지만 유사배열로 `forEach` 를 사용할 수 있다.
1. 유사배열에 대한 참조나 간단한 인용
2. `forEach()` 가 아닌 다른 루프를 돌릴 수 있는 방법

위 2가지 추가 부탁드립니당

2021-06-16 12:19 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +const newTag = document.createElement('Tag')
인자로 태그를 넘겨준다는 설명에 오류는 없을까요?
심바가 표현한 태그는 무엇을 의미할까요?

2021-06-16 12:19 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +가장 대표적인 방법은 `appendChild` 를 사용하는 것이다. 부모 elem 의 자식 elem 중 마지막 자식으로 elem 를 추가한다.
지속적으로 부모의 자식이라는 표현이 나오는데 이게 옳은 표현일까요?

2021-06-16 12:19 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +그 외에도 `insertBefore` 를 사용하면, 부모 elem 의 자식 중 기준이 되는 자식(reference)의 앞에 elem 를 추가 할 수 있다.
기준이 되는 자식을 `Reference`로 표현한 이유가 있으실까요?

2021-06-16 12:19 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +id, className 혹은 tag 등을 이용해 원하는 elem 찾는 `getElementsBy*` 도 있지만,
심바가 생각하는 `tag`는 무엇일까 계속 궁금해지는군요?!

2021-06-16 12:19 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +또한 `newTag.id` 혹은 `newTag.classList` 처럼 elem 속성 값에 직접 접근할 수 도 있다.
직접 접근하는 방법을 추천하는 것일까요?
그게 좋지 않다는 것은 레벨1에서 주로 나오는 피드백인데 조금 더 설명을 추가하는게 어떨까요?

2021-06-16 12:19 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +그래서 이번에는 Vanilla JavaScript에서 innerHTML을 사용하지 않고,
이번에 작성된 아티클 주제를 선정한 동기? 로 느껴지는데 메세지를 좀 더 담아주실 수 있을까요?

2021-06-16 12:19 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +element.removeChild()
위에서는 `parentElement`라는 표현이 많은데
여기서는 왜 `parentElement`라고 표현하시지 않으셨나요?

2021-06-16 12:19 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +```
`html` 코드 스니펫임을 지정해주시는게 어떨까요?

2021-06-16 12:19 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +```javascipt
지속적인 오타로 코드 하이라이팅이 되지 않고 있네요

2021-06-17 07:43 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +그 외에도 `insertBefore` 를 사용하면, 부모 elem 의 자식 중 기준이 되는 자식(reference)의 앞에 elem 를 추가 할 수 있다.
MDN 문서에서 insertBefore() 의 설명에서 기준이 되는 자식 노드에 reference라고 되어있어서 사용하게되었습니다.

표현이 어색한가요..?

2021-06-17 08:07 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +const newTag = document.createElement('Tag')
'tag'는 요소 자체를 의미하기 때문에 'tagName'이라는 표현이 더 맞았던 것 같습니다.

2021-06-17 08:08 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +이때 반환된 elem 들은 NodeList로 반환되며, Array는 아니지만 유사배열로 `forEach` 를 사용할 수 있다.
위 내용들을 추가하였습니다. 🙂

2021-06-17 08:09 UTC, devJang commented on src/content/post/2021-05-09-handle-dom-element.md
> +그 외에도 `insertBefore` 를 사용하면, 부모 elem 의 자식 중 기준이 되는 자식(reference)의 앞에 elem 를 추가 할 수 있다.
굳이 부모의 자식이라고 돌아갈 필요없이 한번에 부를 수 있는 방법이 있지요?!

2021-06-17 08:10 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +DOM에 element(이하 elem)를 추가하고, 다루는 방법에 대해 예시를 통해 알아보려고 한다.
큰 차이가 없네용.. 수정하였습니다. 🙂

2021-06-17 08:10 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +const targetElement = querySelector('Target')
잘 확인하겠습니다.. 🥲

2021-06-17 08:11 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +```javascipt
세상에.. 최악이네요.. 죄송합니다.. 😭

2021-06-17 08:14 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +id, className 혹은 tag 등을 이용해 원하는 elem 찾는 `getElementsBy*` 도 있지만,
해당 부분도 'tagName'으로 수정하였습니다.

2021-06-17 08:14 UTC, 0imbean0 commented on src/content/post/2021-05-09-handle-dom-element.md
> +element.removeChild()
이 부분도 잘 확인했어야하는데.. 🥲

2021-08-15 06:26 UTC, merged