[미키] SWR, 서버 데이터를 로컬 데이터처럼 관리해보자
woowacourse/tecoble pull request #362
Opened 2021-05-23 14:28 UTC by 0307kwon

초고 작성했습니다 ㅎㅎ

잘부탁드립니다! 😁

2021-05-25 06:37 UTC, dusdn1702 approved these changes
글 정말 잘 읽었습니다 미키!!!👍👍
잘 모르는 내용인데도 이해하기 쉽네요 ㅎㅎㅎ
제가 크게 드릴 피드백이 없네요....ㅠㅠ 
그래서 그냥 approve 하겠습니다!!!!

2021-05-25 06:37 UTC, dusdn1702 commented on src/content/post/2021-05-23-swr.md
> +물론 커스텀 훅에 useEffect를 포함시켜 추상화할 수 있겠지만 그렇게 구현하는데에도 품이 많이 든다.
혹시 품이 많이 든다는게 뭘까요..? 비용이 많이 든다..?

2021-05-25 06:37 UTC, dusdn1702 commented on src/content/post/2021-05-23-swr.md
> +좀 어렵게 다가올 수 있다. 그리고 이런 의문이 들 수 있다.
정말 어렵네요...😭

2021-05-25 06:37 UTC, dusdn1702 commented on src/content/post/2021-05-23-swr.md
> +빠르게 **SWR을 왜 사용하는지**에 대한 주제로 넘어가보자
```suggestion
빠르게 **SWR을 왜 사용하는지**에 대한 주제로 넘어가보자.
```

2021-05-25 06:44 UTC, dusdn1702 commented on src/content/post/2021-05-23-swr.md
> +하지만 SWR은 request의 중복을 자동으로 제거해주기 때문에
이 코드는 SWR을 사용하지 않는 코드일까요??
그렇다면 SWR을 사용하는 코드를 추가한다면 어떨까요??

2021-05-25 06:49 UTC, TaewanKimmmm approved these changes
배경 지식이 없어서 힘들었지만 어느 정도의 배경 지식이 있는 사람들이라면 이해하기 쉽게 글을 잘 써주신 것 같아요! 독자 입장에서 생각하신 것이 느껴졌네요 ㅎㅎㅎ
좋은 글 잘 읽었습니다!👍👍👍👍👍👍

2021-05-25 06:49 UTC, TaewanKimmmm commented on src/content/post/2021-05-23-swr.md
> +그래서 오늘은 이 불편함을 어느정도 해소할 수 있는 `SWR`에 대해서 알아보도록 하자.
조금 더 명시적으로 Redux로 서버 데이터 관리하는 데 있어서의 불편함과 이를 해소할 수 있는 `SWR`에 대해서 알아보도록 하자.라고 표현하는 것도 좋을 것 같아요!🙏

2021-05-25 06:49 UTC, TaewanKimmmm commented on src/content/post/2021-05-23-swr.md
> +`SWR이 그래서 대체 뭐가 좋은데?`
오..제 속마음을 읽으셨네요..👍

2021-06-12 08:12 UTC, 0307kwon commented
파피 샐리 모두 피드백 감사합니다!! 전반적으로 피드백 반영해보았습니다 ㅎㅎ 🧡

2021-06-12 08:14 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +물론 커스텀 훅에 useEffect를 포함시켜 추상화할 수 있겠지만 그렇게 구현하는데에도 품이 많이 든다.
표현 수정하였습니다! 😁

2021-06-12 08:15 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +하지만 SWR은 request의 중복을 자동으로 제거해주기 때문에
SWR을 사용하는 코드인데 설명이 조금 부족했던 것 같네용 ㅠㅜ
감사합니다! 좀 더 구체적으로 표현해주었습니다 ㅎㅎ

2021-06-12 08:15 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +그래서 오늘은 이 불편함을 어느정도 해소할 수 있는 `SWR`에 대해서 알아보도록 하자.
좀 더 명확하네요! 감사합니다 ㅎㅎ

2021-06-13 05:44 UTC, jho2301 reviewed
안녕하세요 미키 
SWR글 잘 봤습니다~~ 
SWR은 안 써보고 비슷한 역할을 하는 리액트쿼리만 사용해봤는데 동작도 상당히 유사한 라이브러리네요 .
몇 가지 수정사항 남겨요. 
꼭 고쳐야된다는 아니고 의견일 뿐이니, 자유롭게 의견 남겨주세요

2021-06-13 05:44 UTC, jho2301 commented on src/content/post/2021-05-23-swr.md
> +이제 코드는 점점 복잡해지기 시작한다.
1. 헤더내용을 바꾸면 어떨까요?

    리덕스도 fetch 데이터를 전역적으로 사용가능하기 때문에, 불편함 or 차이점으로 적절하지 않은 것 같습니다. 
    내용을 보면 서버상태 최신화/갱신에 대한 이야기로 전환할 수 있을 것 같은데, `상태 최신화를 위한 코드가 중복된다`로 바꾸면 어떨까요?
 
2. 예시 코드가 보강되면 어떨까요?
    
      thunk함수 선언부는 1번의 예시로 옮기는게 적절할 것 같고,
      실제 컴포넌트에는 예시의 useEffect함수 세 줄이 필요한 것일텐데,  2번 주장의 예시로는 잘 안와닿는 것 같습니다. 상태 갱신을 위해서 컴포넌트에서 각각 API콜을 한다면 SWR도 비슷한 코드량이 필요하지 않을까요?
      
      > 여기서 추가적으로 1분마다, 또는 네트워크가 재연결되었을 때 데이터를 갱신시켜주어야한다면?
      
      저는 이쪽에 대한 내용을 중심으로 보강하면 어떨까해요.
      위 내용에 대한  간단한 예시가 추가된다면 좀 더 설득력을 얻게 되지 않을까 싶습니다!

2021-06-13 05:44 UTC, jho2301 commented on src/content/post/2021-05-23-swr.md
> +key는 다른 서버 데이터와 구분할 수 있는 이름과 request를 보낼 주소로 사용된다.
저는 key라는 인자가 각 fetch의 캐시데이터를 구분하기 위한 유니크한 key 값으로 사용되는 것으로 파악했어요.
1. `캐시`라는 키워드가 중요한 것 같아서 들어가는게 좋지 않을까 생각하는데 어떻게 생각하시나요?
2. `requset를 보낼 주소로 사용된다`라는 설명이 적확한지 궁금합니다!  레퍼런스가 있다면 공유해주시면 감사하겠습니다. 지금 생각으로는 저렇게 사용하는건 스펙보다는 컨벤션 때문이지 않은가 생각이드네요

제가 찾은 레퍼런스입니다~ https://swr.vercel.app/docs/options

2021-06-13 05:54 UTC, jho2301 commented on src/content/post/2021-05-23-swr.md
> +### 2. 상황에 따른 data fetching를 편리하게 사용할 수 있다.
refetch에 대한 내용이 아닌가 싶어요

그래서 헤더도 갱신, 최신화, refetch 느낌의 키워드가 들어가는게 어떨까요?

2021-06-13 11:44 UTC, GwangYeol-Im requested changes
안녕하세요 미키, 글 잘 읽었습니다 :) 우선 저는 '이 글을 어떤 독자가 읽을까' 생각해보았을 때, 다음과 같이 예상을 해보았어요.

- 상태 관리에 어느정도 이해도를 가지며 해당 라이브러리에 관심이 있는 개발자

현재 제가 딱 이 입장이라 좀 더 독자에 이입해서 글을 읽어본 뒤 느낀 점을 짧게 말하자면,

- 중간중간 예시 코드가 삽입되어 있지만, Pseudo code나 주석 없이 코드의 나열만으로 관련 설명에 빗대어 추론하려고 하니 이해가 쉽지는 않았습니다.
- `SWR`을 사용하고 싶은 누군가가 반드시 리덕스를 경험해보았을 거라는 추측은 조금 섣부르지 않나 싶어요! 만약 대조를 목적으로 작성하고 싶었던 거라면 `Prerequisite` 단락을 통해 이 글을 읽기 위한 필요 지식을 간략히 안내해도 좋지 않았을까 싶네요 :)
- 두 번째 느낀 점의 연장선이긴 한데, 글의 성격을 `리덕스 - SWR의 대조` 와 `SWR 스펙 설명` 중 하나에 집중해서 글을 풀어보면 어떨까요? 타겟을 좁혀 깊게 글을 써보면 글을 작성하는 미키 또한 얻어가는 게 많을 것 같아요! (물론 쉽지는 않겠지만요 ㅠ 저도 이 부분은 많이 노력해야 하는 부분이라..)

그 외에도 맞춤법, 띄어쓰기도 좀 더 신경 써주면 좋을 것 같습니다 :)   
쓰다보니 피드백이 많아지는 듯해 리뷰는 여기에서 마치도록 할게요.   
모든 부분을 받아드릴 필요는 없습니다! 잘 취사 선택해서 더 좋은 글 작성 부탁드릴게요🙌   
수고 많으셨습니다!

2021-06-13 11:44 UTC, GwangYeol-Im commented on src/content/post/2021-05-23-swr.md
> +author: [3기_미키]
이 포스트 뿐만 아니라 이전에 작성한 글, `author.yaml`에 위치한 네이밍 컨벤션 또한 변경하는 것이 좋을 것 같아요 :) 현재는 dev server에서 해당 포스트를 확인할 수 없네요!

2021-06-13 11:44 UTC, GwangYeol-Im commented on src/content/post/2021-05-23-swr.md
> +가장 큰 문제라고 해도 과언이 아니다.
프론트엔드에서 이 문제가 왜 가장 큰 문제일까요?? 👀 만약 해당 포스트의 중요성을 암시하기 위해 작성한 문장이었다면, 이 주장을 뒷받침할 근거가 필요하지 않을까 싶어요 ㅎ.ㅎ

2021-06-13 11:44 UTC, GwangYeol-Im commented on src/content/post/2021-05-23-swr.md
> +=> fetch 후 redux에 dispatch하는 과정을 거쳐야하고 dispatch를 위한 액션 타입도 만들어줘야하는 등 불편함이 많다.
저도 이 부분에 대해서 코멘트 남기려 했는데 파노가 미리 남겨 주었네요 ㅎㅎ

- Pseudo code가 아닌, 특정 프로젝트의 예시 코드를 발췌한 점
- 코드의 선언부가 아닌 사용부를 예시로 든 점

이 두 부분을 고려 하였을 때, 해당 예시가 잘 와닿을 수 있을까?라는 의문이 살짝 들었던 것 같아요. 🤔

2021-06-13 11:44 UTC, GwangYeol-Im commented on src/content/post/2021-05-23-swr.md
> +> 초 값은 클라이언트가 최신이 아닌 응답을 받아 들일 시간을 나타냅니다.
이 부분은 `SWR`에 대한 저의 이해도가 낮은 것일 수도 있겠지만, 번역투로 되어있는 이 문장이 무엇을 설명하고 싶은 건지 잘 모르겠네요 ㅠㅠ '최신이 아닌 응답을 받아 들인다'는 말은 어떤 의미일까요? 지식을 설명하는 데 있어 필자의 해석이 들어가는 것은 최대한 지양하는 것이 좋지만, 적절한 의역으로 표현을 가다듬는 과정은 필요하지 않을까 싶네요 ㅎㅎ

2021-06-14 03:01 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +=> fetch 후 redux에 dispatch하는 과정을 거쳐야하고 dispatch를 위한 액션 타입도 만들어줘야하는 등 불편함이 많다.
두 분의 말씀을 듣고 다시 보니 확실히 이게 와닿을 만한 코드인가...? 라는 생각이 드네요!!
특정 프로젝트에서의 예시 코드 보다는 일반적인 코드로 변경하고
리덕스 코드를 축약해서 작성해보았습니다! 👍👍👍

2021-06-14 03:53 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +이제 코드는 점점 복잡해지기 시작한다.
이 부분은 제가 의미 전달을 잘못한것 같습니다 ㅠㅜ😭 제가 다시 읽어봐도 이해가 안가네요 ㅋㅋㅋㅋ
swr은 상태 초기화 코드가 추가적으로 필요가 없으며 useSWR()을 상태가 필요한 컴포넌트에서 사용해주기만 하면
상태 초기화 코드 없이 상태를 가져올 수 있고 상태 초기화는 내부적으로 해주는 특징을 가지는 것으로 알고 있습니다!

예시와 설명을 조금 수정해보았는데 이런 방식도 괜찮을까요?! 😊

2021-06-27 14:00 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +key는 다른 서버 데이터와 구분할 수 있는 이름과 request를 보낼 주소로 사용된다.
파노 말대로 key 값을 반드시 주소로 사용해야하는 것은 아닌 것 같습니다!
글의 느낌이 무조건 주소로 사용해야한다는 느낌이 강하네요
설명에 `일반적으로` 라는 말을 덧붙이고 왜 key 값으로 주소를 사용하는 것이 일반적인지에 대한 설명을 추가했습니다!
고마워요 파노! 👍👍

레퍼런스
https://swr.vercel.app/#overview
https://swr.vercel.app/docs/arguments

2021-06-27 14:32 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +### 2. 상황에 따른 data fetching를 편리하게 사용할 수 있다.
`데이터 갱신을 위한 re-fetching을 간단히 구현할 수 있다.`로 수정해보았습니다! 😁

2021-06-27 16:23 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +가장 큰 문제라고 해도 과언이 아니다.
감사합니다! 조금 더 글이 매끄러워진 것 같아요 👍👍

2021-06-27 16:28 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +> 초 값은 클라이언트가 최신이 아닌 응답을 받아 들일 시간을 나타냅니다.
> 비동기 적으로 백그라운드에서 새로운 데이터로 체크인하는 동안 클라이언트가 **최신이 아닌 데이터를 사용할 것**임을 나타냅니다.
> 초 값은 클라이언트가 최신이 아닌 데이터를 사용할 시간을 나타냅니다.

라고 수정해보았습니다! 조금 더 의미 전달이 명확해졌을까요? 😁

2021-06-27 16:40 UTC, 0307kwon commented
@jho2301 @GwangYeol-Im 피드백 주신 내용 반영해보았습니다!
확인부탁드립니다 ㅎㅎ 🧡

2021-06-28 00:41 UTC, GwangYeol-Im approved these changes
글이 전체적으로 많이 매끄러워졌네요! 이 글의 퇴고를 위해 미키가 얼마나 고심 했는지 잘 알 수 있었습니다. 👏🏻👏🏻 코멘트를 몇 개 남겨놓았는데 내용적으로 크게 중요한 부분은 아니나, 스타일이나 일관성을 보충해줄 수 있는 방향으로 제안드려 봅니다. 한번 확인 부탁드리고 제 리뷰는 이 쯤에서 마치도록 할게요 :)

2021-06-28 00:41 UTC, GwangYeol-Im commented on src/content/post/2021-05-23-swr.md
> +이를 해소할 수 있는 `SWR`에 대해서 알아보도록 하자.
```suggestion
그래서 오늘은 데이터를 관리함에 있어 기존 `Redux의 단점`과
이를 해소할 수 있는 `SWR`에 대해서 알아보려고 한다.
```
좀 더 자연스러운 방향으로 제안드려봅니다!

2021-06-28 00:41 UTC, GwangYeol-Im commented on src/content/post/2021-05-23-swr.md
> +      <p>userData.age</p>
```suggestion
      <h2>{userData.name}</h2>
      <p>{userData.age}</p>
```

☺️

2021-06-28 00:41 UTC, GwangYeol-Im commented on src/content/post/2021-05-23-swr.md
> +2. 만약 유저 데이터를 Page1, Page2, Page3에서 모두 사용하고 있다면 사용자가 어떤 페이지 url로 가장 먼저 접근할지 개발자는 알 수 없으니, 모든 페이지에서 상태 초기화 코드를 작성하여야 한다.
문제점을 제시하기 위한 Bad Case를 가정하는 부분은 이해하지만, 가장 상위의 App 컴포넌트 단에서 데이터를 가져오는 방식도 있지 않을까요? 🤔 크게 잘못된 부분은 아니기에 한번 고려만 해보는 걸 추천드립니다 ㅎㅎ

2021-06-28 00:41 UTC, GwangYeol-Im commented on src/content/post/2021-05-23-swr.md
> +또한, 브라우저에 Focus를 하면 정보를 갱신하는 것이 default 설정으로 들어가 있고
브라우저 관점으로 바라본다는 의미인가요? 👀

2021-06-28 00:41 UTC, GwangYeol-Im commented on src/content/post/2021-05-23-swr.md
> +### 3. fetch data가 캐쉬, 공유되기 때문에 불필요한 request를 줄일 수 있다.
캐쉬 - 캐시가 혼용되고 있네요 :) 단어에 대한 일관성을 맞추어주면 좋을 것 같아요! 아님 혹시 의도하신 바가 있었을까요?

2021-06-28 00:50 UTC, jho2301 approved these changes
미키! 수정한 내용 잘 봤습니다.
고생하셨어요 어프루브 남깁니다

2021-06-28 11:38 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +      <p>userData.age</p>
오우야 꼼꼼하게 봐주어서 고맙습니다! 👍👍👍

2021-06-28 11:40 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +### 3. fetch data가 캐쉬, 공유되기 때문에 불필요한 request를 줄일 수 있다.
그러게요...? 저 왜 혼용하고 있죠...? 👀 날카로운 피드백 감사합니다! 👍👍👍

2021-06-28 11:42 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +또한, 브라우저에 Focus를 하면 정보를 갱신하는 것이 default 설정으로 들어가 있고
`사용자가 브라우저에 focus를 하면` 입니다! 확실히 오해할만 하네요 감사합니닷! 👍

2021-06-28 11:47 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +2. 만약 유저 데이터를 Page1, Page2, Page3에서 모두 사용하고 있다면 사용자가 어떤 페이지 url로 가장 먼저 접근할지 개발자는 알 수 없으니, 모든 페이지에서 상태 초기화 코드를 작성하여야 한다.
가장 상위의 컴포넌트 단에서 데이터를 가져왔을 때의 문제는 서버 데이터를 가져오지 않아도 될 때에도 무조건 가져온다는 점이 있을 것 같습니다
예를 들어 page4로 가장 먼저 접근했는데 page4에서는 유저 정보를 가져오지 않아도 되는 페이지였음에도 불구하고
유저 데이터를 가져온다는 점이 있겠네요! 피드백 감사합니다! 🧡

2021-06-28 11:52 UTC, 0307kwon commented
포코! js 내부 데이터를 어떻게 말하는게 찰떡일지 고민이 되었는데
리덕스 소개 페이지에서는 `앱`이라는 용어를 많이 사용하는 것 같아
`로컬` -> `앱` 으로 수정해보았습니다!

생각하시기에 좀 더 명확한 용어가 있으면 또 수정해보겠습니다 😁

2021-06-28 13:12 UTC, devJang approved these changes
너무 고생많으셨습니다ㅠㅠ
저는 미키가 내재화한 것을 글로 작성하여 표현했을때 독자들도 납득하거나
납득되지 않을때는 독자와 토론을 주고 받는 것이 가능한 수준만 된다면 괜찮다고 생각합니다.
피드백 주신 모든 크루분들에게도 감사해요

2021-06-29 12:12 UTC, 0307kwon commented on src/content/post/2021-05-23-swr.md
> +이는 [HTTP 리소스에 대한 명세 - RFC 5861](https://datatracker.ietf.org/doc/html/rfc5861)에서 정의한
RFC 5861 내용을 요약해보았습니다! 감사합니다~ 😊

2021-06-29 12:20 UTC, merged