[완태] Email 보내기에 비동기, 이벤트를 곁들인.
woowacourse/tecoble pull request #499
Opened 2021-08-01 12:49 UTC by wannte

## PR 체크 리스트
### 내용
- [x] 기술 용어를 통일했는가? - 영어, 한글 혼용 여부
- [x] 레퍼런스 형식을 통일했는가? - 레퍼런스는 글 마지막에 리스트 형식으로 작성
- [x] 글이 주제에 맞는 흐름으로 진행되었는가?
- [x] 태그가 올바르게 달려있는가?
- [x] 모든 리소스들에 대해 출처를 작성했는가?

### 스타일
- [x] 한 문장의 호흡이 너무 길지는 않은가?
- [x] 마크다운 문법과 맞춤법을 잘 준수하였는가?

<br/>

## 리뷰어에게 할 말
늦었네요! 편하게 피드백 부탁드려요!
<br/>

Close #477

2021-08-01 13:22 UTC, hybeom0720 approved these changes
안녕하세요! 완태
저번 글에 이어서 메세징 처리에 대한 글 잘 읽었습니다.

내용에서 크게 수정하기 보다는 표현 부분에서 피드백을 남겼습니다.

추가로 ``` 틱의 짝이 안맞는 것 같기도 한데, 확인 부탁드릴게요!

2021-08-01 13:22 UTC, hybeom0720 commented on src/content/post/2021-07-31-email-async-event.md
> +MailSender로 충분하지만, Html Template을 활용하여 메일을 보내는 것을 목표로 두기 때문에 JavaMailSender를 사용한다. 또한, 별도의 메일 서비스를
두 개를 명확히 비교해줘서 좋은 것 같습니다

2021-08-01 13:22 UTC, hybeom0720 commented on src/content/post/2021-07-31-email-async-event.md
> +우리의 서비스의 경우, job을 취소가 완료되는 것이 중요한 부분이었고, 메일의 도착 여부와 관계없이 job이 취소된 경우에는 OK 요청을 보내주어야 했다. 메일 전송 완료를 기다리기 위해 클라이언트가 응답을 늦게 받는 상황을 없애고 싶었고, 그러기 위해 비동기 처리를 도입하게 되었다.
오 스토리 텔링이 좋은 것 같습니다.
왜 메일을 비동기로 보내야하는지 알 것 같아요.

2021-08-01 13:22 UTC, hybeom0720 commented on src/content/post/2021-07-31-email-async-event.md
> +`@EnableAsync` 옵션만 주어도, 비동기 처리를 사용할 수 있다. 이를 Customizing 하기 위해서 위처럼, AsyncConfigurer를 구현한 설정 파일을 만들어 줄 수도 있다. 별도 설정을 하지 않은 경우, CorePoolSize 는 1, MaxPoolSize, QueueCapacity는 `Integer.MAX_VALUE` 로 정의되어
부가적인 설명이긴한데, 
```suggestion
Java Spring에서는 `@EnableAsync` 옵션만 주어도, 비동기 처리를 사용할 수 있다. 이를 Customizing 하기 위해서 위처럼, AsyncConfigurer를 구현한 설정 파일을 만들어 줄 수도 있다. 별도 설정을 하지 않은 경우, CorePoolSize 는 1, MaxPoolSize, QueueCapacity는 `Integer.MAX_VALUE` 로 정의되어 있고, warning 레벨의 log를 출력하도록 설정이 되어 있다.
```
을 추가하여 일반 자바와는 다르다는 것을 강조하는 것도 좋을 것 같습니다.

2021-08-01 13:22 UTC, hybeom0720 commented on src/content/post/2021-07-31-email-async-event.md
> +위에는 비동기 처리를 위한 쓰레드를 별도로 생성해주는 설정 파일이고, 특정 메소드를 비동기 처리해주기 위해서 아래와 방식으로 메소드 위에 `@Async` 어노테이션을 붙여주면 된다. 별도로 명시해주면, 특정 쓰레드를 지정해줄 수도 있다. (클래스에 어노테이션을 붙여줄 시 전체 메소드에 적용)
설정 파일과 Bean에서의 Annotation 차이를 설명해주시는 것도 좋은 것 같습니다.

2021-08-01 13:22 UTC, hybeom0720 commented on src/content/post/2021-07-31-email-async-event.md
> +위에는 비동기 처리를 위한 쓰레드를 별도로 생성해주는 설정 파일이고, 특정 메소드를 비동기 처리해주기 위해서 아래와 방식으로 메소드 위에 `@Async` 어노테이션을 붙여주면 된다. 별도로 명시해주면, 특정 쓰레드를 지정해줄 수도 있다. (클래스에 어노테이션을 붙여줄 시 전체 메소드에 적용)
```suggestion
위에는 비동기 처리를 위한 쓰레드를 별도로 생성해주는 설정 파일이고, 특정 메소드를 비동기 처리해주기 위해서 아래와 방식으로 메소드 위에 `@Async` 어노테이션을 붙여주면 된다. 클래스에 어노테이션을 붙여줄 시에는 해당 클래스의 전체 메소드에 사용이 된다. 별도로 명시해주면, 특정 쓰레드를 지정해줄 수도 있다.
```
글에 괄호가 들어가는 것을 선호하지 않아서 조심스럽게 개인적인 의견을 제시해봅니다.

2021-08-01 13:22 UTC, hybeom0720 commented on src/content/post/2021-07-31-email-async-event.md
> +`EventListener`는 어노테이션을 통해서 구현이 가능한데, `TransactionalEventListener`를 활용하면, `TransactionaPhase`에 따른 EventListen 시점을 선택할 수 있다. 우리 서비스의 경우, AFTER_COMMIT(DB에 반영된 후)에 Event를 듣도록 설정이 되어 있다. JobEvent의 상속구조를
```suggestion
`EventListener`는 어노테이션을 통해서 구현이 가능한데, `TransactionalEventListener`를 활용하면, `TransactionaPhase`에 따른 Event 듣도록 시점을 선택할 수 있다. 우리 서비스의 경우, AFTER_COMMIT(DB에 반영된 후)에 Event를 듣도록 설정이 되어 있다. JobEvent의 상속구조를 통해 여러 가지 상황(예약, 취소, 시작, 종료)을 하나의 메소드로 처리할 수 있다.
```
한글, 영어 용어 통일하는 것이 좋을 것 같습니다.

2021-08-01 13:22 UTC, hybeom0720 commented on src/content/post/2021-07-31-email-async-event.md
> +`ApplicationEventPublisher`, `EventListener`을 이용하여 이벤트 발행과 처리 로직을 분리하다.
관심사를 분리하는 것이 AOP 관점인 것 같은데, 해당 설명을 덧붙히면 어떨까? 라는 생각이 듭니다.
하지만 이벤트 발행에 조금 더 초점을 맞추고 싶으면 이대로 진행하셔도 좋을 것 같습니다.

2021-08-01 18:15 UTC, da-nyee requested changes
안녕하세요, 완태!

이메일, 비동기, 이벤트.. 생소한 내용을 잘 다뤄주셨네요 👍
다음에 이런 식으로 사용할 일이 있으면 이 글을 참고해야겠습니다!

코멘트 몇 개 남겼어요.
확인하고 반영해주시면 감사하겠습니다 ~!

2021-08-01 18:15 UTC, da-nyee commented on src/content/post/2021-07-31-email-async-event.md
> +> 테스트 또한 하나의 쓰레드의 작업이 진행되고, 그 쓰레드의 작업이 완료되면, 테스트는 성공한 것으로 표시된다. 즉, 비동기 처리되어 별도의 쓰레드로 처리되는 부분에 대해서는 기존의 방식으로는 테스트를 진행하는 것은 불가하다. 이 부분에 대해서 저자도 공부를 진행해볼 예정이다.
```suggestion
> 테스트 또한 하나의 쓰레드의 작업이 진행되고, 그 쓰레드의 작업이 완료되면 테스트는 성공한 것으로 표시된다. 즉, 비동기 처리되어 별도의 쓰레드로 처리되는 부분에 대해서는 기존의 방식으로는 테스트를 진행하는 것은 불가하다. 이 부분에 대해서 필자도 공부를 진행해볼 예정이다.
```

저자는 책을 지필한 사람의 느낌이라 필자가 더 낫지 않을까 제안해봅니다!

2021-08-01 18:15 UTC, da-nyee commented on src/content/post/2021-07-31-email-async-event.md
> +우리 서비스는 Job의 `예약`, `취소`, `시작`, `종료`의 모든 경우에 대해서 메일을 보내주는 기능이 있다. 만약, 메일 뿐만 아니라 애플리케이션의 알람을 보내주는 로직이 추가된다고 가정해보자. 각각의 메소드에 일일이 추가되는 로직을 추가해줘야 하고, 도메인 로직에 집중하지 못하는 코드가 된다. 이벤트의 방법을 통해, JobService와 Mail
```suggestion
우리 서비스는 Job의 `예약`, `취소`, `시작`, `종료`의 모든 경우에 대해서 메일을 보내주는 기능이 있다. 만약, 메일뿐만 아니라 애플리케이션의 알람을 보내주는 로직이 추가된다고 가정해보자. 각각의 메소드에 일일이 추가되는 로직을 추가해줘야 하고, 도메인 로직에 집중하지 못하는 코드가 된다. 이벤트를 발행하는 방법을 통해 JobService와 MailService의 의존성을 끊어줄 수 있고 확장 가능한 구조가 될 수 있다.
```

`이벤트의 방법`이 어색하게 느껴져서 `이벤트를 발행하는 방법`으로 변경해보는 건 어떨까요?

2021-08-01 18:15 UTC, da-nyee commented on src/content/post/2021-07-31-email-async-event.md
> +`ApplicationEventPublisherAware` 의 구현체는 publishEvent 메소드를 통해 이벤트를 발행할 수 있다.
```suggestion
`ApplicationEventPublisherAware`의 구현체는 publishEvent 메소드를 통해 이벤트를 발행할 수 있다.
```

2021-08-01 18:15 UTC, da-nyee commented on src/content/post/2021-07-31-email-async-event.md
> +`EventListener`는 어노테이션을 통해서 구현이 가능한데, `TransactionalEventListener`를 활용하면, `TransactionaPhase`에 따른 EventListen 시점을 선택할 수 있다. 우리 서비스의 경우, AFTER_COMMIT(DB에 반영된 후)에 Event를 듣도록 설정이 되어 있다. JobEvent의 상속구조를
```suggestion
`EventListener`는 어노테이션을 통해서 구현이 가능한데, `TransactionalEventListener`를 활용하면, `TransactionaPhase`에 따른 EventListen 시점을 선택할 수 있다. 우리 서비스의 경우 AFTER_COMMIT(DB에 반영된 후)에 Event를 듣도록 설정이 되어 있다. JobEvent의 상속구조를 통해 여러 가지 상황(예약, 취소, 시작, 종료)을 하나의 메소드로 처리할 수 있다.
```

2021-08-01 18:15 UTC, da-nyee commented on src/content/post/2021-07-31-email-async-event.md
> +지금까지, Email에 비동기와 이벤트 발행을 적용해 보았다. AOP를 활용하게 되면, publishEvent의 메소드 없이 어노테이션만으로도 동일한 작업을 할 수 있다고 한다.
```suggestion
지금까지 Email에 비동기와 이벤트 발행을 적용해 보았다. AOP를 활용하게 되면, publishEvent의 메소드 없이 어노테이션만으로도 동일한 작업을 할 수 있다고 한다.
```

2021-08-01 18:15 UTC, da-nyee commented on src/content/post/2021-07-31-email-async-event.md
> +이 부분에 대해 더 공부해보고 싶은 분은 이 [블로그](https://supawer0728.github.io/2018/03/24/spring-event)를 추천하다. 도메인에만 더욱더 집중할 수 있는 그런 코드가 될 수 있을 것으로 생각한다.
```suggestion
이 부분에 대해 더 공부해보고 싶은 분은 이 [블로그](https://supawer0728.github.io/2018/03/24/spring-event)를 추천한다. 도메인에만 더욱 더 집중할 수 있는 그런 코드가 될 수 있을 것으로 생각한다.
```

2021-08-01 18:15 UTC, da-nyee commented on src/content/post/2021-07-31-email-async-event.md
> +이 부분에 대해 더 공부해보고 싶은 분은 이 [블로그](https://supawer0728.github.io/2018/03/24/spring-event)를 추천하다. 도메인에만 더욱더 집중할 수 있는 그런 코드가 될 수 있을 것으로 생각한다.
> 도메인에만 더욱더 집중할 수 있는 그런 코드가 될 수 있을 것으로 생각한다.

AOP를 활용하면 도메인에 더 집중하는 코드가 된다는 뜻인가요?

2021-08-02 02:44 UTC, wannte commented on src/content/post/2021-07-31-email-async-event.md
> +위에는 비동기 처리를 위한 쓰레드를 별도로 생성해주는 설정 파일이고, 특정 메소드를 비동기 처리해주기 위해서 아래와 방식으로 메소드 위에 `@Async` 어노테이션을 붙여주면 된다. 별도로 명시해주면, 특정 쓰레드를 지정해줄 수도 있다. (클래스에 어노테이션을 붙여줄 시 전체 메소드에 적용)
설정 파일가 쓰레드를 생성한다면, Async Annotation은 이를 사용한다의 표현을 하고 싶었는데, 지금의 문장에서는 모호하게 표현이 되었군요! 좋은 피드백 감사합니다.

2021-08-02 02:47 UTC, wannte commented on src/content/post/2021-07-31-email-async-event.md
> +위에는 비동기 처리를 위한 쓰레드를 별도로 생성해주는 설정 파일이고, 특정 메소드를 비동기 처리해주기 위해서 아래와 방식으로 메소드 위에 `@Async` 어노테이션을 붙여주면 된다. 별도로 명시해주면, 특정 쓰레드를 지정해줄 수도 있다. (클래스에 어노테이션을 붙여줄 시 전체 메소드에 적용)
오 좋은 것 같아요! 특정쓰레드를 명시해주는 scope에 클래스 단위의 어노테이션도 포함되는 부분이라 지금처럼 뒤로 빼는 구성이 좋을 것 같네요

2021-08-02 02:50 UTC, wannte commented on src/content/post/2021-07-31-email-async-event.md
> +`ApplicationEventPublisher`, `EventListener`을 이용하여 이벤트 발행과 처리 로직을 분리하다.
네 사실 AOP의 관점을 공부하고 글에 담아내고자 하는 노력을 했었습니다. (고거 때문에 요청도 늦어졌다고..)

아직 AOP를 익숙하게 다룰 수 있지도 않고, 글의 호흡이 길어질 수 있다고 판단해서, 별도로 분리하고자 했습니다.

아마 추후에 글로 SpringAop 와 AspectJ 를 비교해보는 글을 적어볼까 고민중이에요!

2021-08-02 02:51 UTC, wannte commented on src/content/post/2021-07-31-email-async-event.md
> +사용하지 않고 Gmail 개인 계정을 사용하고 진행하였다. (보안 수준이 낮은 앱 허용 진행하여야 한다) 이 부분을 다루고 있는 블로그가 많으므로 코드를 남겨두고 별도의 설명은 생략한다.
구글 설정을 변경한다는 내용인데, 오히려 혼란을 야기할 수 있다고 생각이 되네요!

tmi의 느낌도 나고, 삭제 하는게 더 좋아 보일 것 같아요!

2021-08-02 02:52 UTC, wannte commented on src/content/post/2021-07-31-email-async-event.md
> +    mailSender.setPort("587);
:sob:

2021-08-02 02:52 UTC, wannte commented on src/content/post/2021-07-31-email-async-event.md
> +> email, password를 github 저장소에 올리기 부담될 때에는 __private-submodule__을 사용해 보기를 추천한다.
그거 노린거에요 ㅎㅎ 미리 링크 만들어 둬야지

2021-08-02 02:55 UTC, wannte commented on src/content/post/2021-07-31-email-async-event.md
> +우리 서비스는 Job의 `예약`, `취소`, `시작`, `종료`의 모든 경우에 대해서 메일을 보내주는 기능이 있다. 만약, 메일 뿐만 아니라 애플리케이션의 알람을 보내주는 로직이 추가된다고 가정해보자. 각각의 메소드에 일일이 추가되는 로직을 추가해줘야 하고, 도메인 로직에 집중하지 못하는 코드가 된다. 이벤트의 방법을 통해, JobService와 Mail
오호 좋습니다!

2021-08-02 02:57 UTC, wannte commented on src/content/post/2021-07-31-email-async-event.md
> +`EventListener`는 어노테이션을 통해서 구현이 가능한데, `TransactionalEventListener`를 활용하면, `TransactionaPhase`에 따른 EventListen 시점을 선택할 수 있다. 우리 서비스의 경우, AFTER_COMMIT(DB에 반영된 후)에 Event를 듣도록 설정이 되어 있다. JobEvent의 상속구조를
`우리의 서비스는` 으로 명확한 표현으로 수정할까 해요!

2021-08-02 02:58 UTC, wannte commented on src/content/post/2021-07-31-email-async-event.md
> +이 부분에 대해 더 공부해보고 싶은 분은 이 [블로그](https://supawer0728.github.io/2018/03/24/spring-event)를 추천하다. 도메인에만 더욱더 집중할 수 있는 그런 코드가 될 수 있을 것으로 생각한다.
넵! 세세한 피드백 감사합니다!

2021-08-02 06:21 UTC, da-nyee approved these changes
완태 피드백 반영 확인했습니다!!
수고하셨습니다 👏👏

2021-08-09 23:48 UTC, gracefulBrown reviewed
사용 예시부터 따라하기 좋게 잘 작성해주셨습니다 :) 
코멘트 남기니 확인 해주신 후 요청주세요~

2021-08-09 23:48 UTC, gracefulBrown commented on src/content/post/2021-07-31-email-async-event.md
> +- Java Doc
Java Doc의 어느 부분을 참고했는지 적어주면 좋을 것 같아요 :)
참고로 링크를 사용하실 수 도 있습니다!

ex) String
https://docs.oracle.com/javase/8/docs/api/java/lang/String.html

2021-08-11 23:58 UTC, gracefulBrown approved these changes

2021-08-11 23:58 UTC, merged