[와이비] JVM에 관하여 - Part 4, Garbage Collection 기초
woowacourse/tecoble pull request #558
Opened 2021-09-02 12:15 UTC by hybeom0720

## PR 체크 리스트
### 내용
- [x] 기술 용어를 통일했는가? - 영어, 한글 혼용 여부
- [x] 레퍼런스 형식을 통일했는가? - 레퍼런스는 글 마지막에 리스트 형식으로 작성
- [x] 글이 주제에 맞는 흐름으로 진행되었는가?
- [x] 태그가 올바르게 달려있는가?
- [x] 모든 리소스들에 대해 출처를 작성했는가?

### 스타일
- [x] 한 문장의 호흡이 너무 길지는 않은가?
- [x] 마크다운 문법과 맞춤법을 잘 준수하였는가?

<br/>

## 리뷰어에게 할 말
GC에 관한 기초적인 글을 작성해보았습니다!
<br/>

Close #536

2021-09-03 07:03 UTC, choijy1705 requested changes
안녕하세요 JVM장인 와이비. 글 잘읽었습니다.
Java를 사용하는 입장에서 정말 유용한 글인 것 같습니다. 이번글에서 유난히 영어로 표기한 부분이 많은데. 이부분을 줄일 수 있는 방법을 생각해보면 좋을 것 같습니다.

2021-09-05 10:16 UTC, wannte approved these changes
요번에도 좋은 주제의 읽기 편한 글을 작성해주셨네요!~

전 바로 어프루브 진행하겠습니다! 몇 가지 코멘트 남겼어요!

2021-09-05 13:02 UTC, hybeom0720 commented on src/content/post/2021-08-30-jvm-gc.md
> +이 때, _mark_ 가 된 영역만 복사되기 때문에 _sweep_ 과정은 이루어지지 않습니다.
이 부분은 공식 용어 인 것 같아서 최대한 원어의 느낌을 살려보고 싶습니다.

2021-09-05 13:30 UTC, hybeom0720 commented on src/content/post/2021-08-30-jvm-gc.md
> +![GC Mark and Sweep](../images/2021-08-30-jvm-mark-and-sweep.png)
정렬하였습니다!

2021-09-05 13:30 UTC, hybeom0720 commented on src/content/post/2021-08-30-jvm-gc.md
> +다음과 같이 메모리를 해제하는 것을 알 수가 있습니다. 하지만 그림에서도 볼 수 있다시피 메모리가 _Fragmentation_ 되는 단점이 있습니다.
추가했스빈다. 좋은 리뷰 감사드립니다!

2021-09-05 13:31 UTC, hybeom0720 commented on src/content/post/2021-08-30-jvm-gc.md
> +이 때, _mark_ 가 된 영역만 복사되기 때문에 _sweep_ 과정은 이루어지지 않습니다.
원래는 해당 부분을 영어로 살려두려고 하였으나...
말씀해주신데로 영어가 너무 자주 나오는데다가, 삭제 및 마크로 해도 글 흐름 상에 문제가 없을 것 같아서 반영했습니다.
더 불어서 여러 부분들을 한글로 고쳐보았습니다.

2021-09-05 13:31 UTC, hybeom0720 commented on src/content/post/2021-08-30-jvm-gc.md
> +새로운 작업을 할 때마다, 두 영역 모두 새로운 데이터들이 메모리에 추가될 가능성이 높습니다.
조금 더 확실하게 표현을 했습니다! 감사합니다.

2021-09-05 13:32 UTC, hybeom0720 commented on src/content/post/2021-08-30-jvm-gc.md
> +메소드가 끝나서 _Stack_ 이 _pop_ 이 되거나, 이렇게 참조하는 객체를 바꾸게 되면 참조되지 않는 객체들이 생겨납니다.
넵! 그래서 설명 추가 및 코드에 주석을 달아두었습니다. 
말씀해주신데로 처음 접하는 사람에게는 생소할것 같아요.
감사합니다!

2021-09-06 08:23 UTC, choijy1705 approved these changes
피드백 반영 고생하셨습니다. 이먼 approve 하겠습니다.

2021-09-06 09:43 UTC, merged