[미키] CSR 앱에서 SSR + CSR 환경으로 이주하기
woowacourse/tecoble pull request #580
Opened 2021-09-18 04:46 UTC by 0307kwon

## PR 체크 리스트
### 내용
- [x] 기술 용어를 통일했는가? - 영어, 한글 혼용 여부
- [x] 레퍼런스 형식을 통일했는가? - 레퍼런스는 글 마지막에 리스트 형식으로 작성
- [x] 글이 주제에 맞는 흐름으로 진행되었는가?
- [x] 태그가 올바르게 달려있는가?
- [x] 모든 리소스들에 대해 출처를 작성했는가?

### 스타일
- [x] 한 문장의 호흡이 너무 길지는 않은가?
- [x] 마크다운 문법과 맞춤법을 잘 준수하였는가?

<br/>

## 리뷰어에게 할 말
늦어서 정말 죄송합니다~!!~!~!~~!~! ㅠㅜㅠㅜㅠ 😭😭😭

<br/>

Close #562

2021-09-18 07:09 UTC, GwangYeol-Im requested changes
글 잘 읽었습니다, 미키! 미키가 직접 겪었던 경험들을 잘 담아주어 SSR 도입 과정에 대해 한번 더 정리할 수 있는 유익한 시간이었습니다. 코멘트로 상세 리뷰 남겨 놓았고, 글 전반적으로 느꼈던 부분을 말씀 드려볼게요 ㅎㅎ

- `앱이 커지는 것`과 `SSR을 도입해야하는 이유`의 상관관계가 크게 와닿지는 않았던 것 같아요! 미키가 서술해준 여러 이유들을 저도 모두 공감하는데요, 이러한 부분은 앱을 설계하는 초기 단계에서 적용해도 충분히 이점을 가져갈 수 있는 부분이라고 생각합니다. 물론 관점의 차이이기 때문에 고려만 해보시고 선택 적용해주시면 감사하겠습니다 :)

경험을 잘 녹여낸 글을 더 잘 표현하면 좋겠다는 마음에 코멘트가 조금 많아진 듯 한데, 모두 수용할 필요는 없습니다! 고생 많았습니다 👍🏻

2021-09-18 07:09 UTC, GwangYeol-Im commented on src/content/post/2021-09-10-ssr.md
> +사용자는 백엔드 서버로 로그인 요청을 보내고 access token과 refresh token을 받아올 것이다. access token은 브라우저에서 다음 사용자 권한이 필요한 요청에서 사용해야 하니 가지고 있어야 할 것이다. 문제는 누군가 내가 로그인한 상태를 기억하고 있어야 다음 웹페이지 접근 시 로그인 상태가 풀리지 않을 것이다. 이 역할을 프론트
```suggestion
사용자는 백엔드 서버로 로그인 요청을 보내고 access token과 refresh token을 받아 온다. 여기서 access token은 사용자 권한이 필요한 요청에서 사용해야 하니 브라우저에서 가지고 있어야 할 것이다. 문제는 누군가 내가 로그인한 상태를 기억하고 있어야 다음 웹페이지 접근 시 로그인 상태가 풀리지 않는다는 것인데, 이 역할을 프론트 서버가 하게 된다.
```
개인적으로 이 문단을 이해하기 위해 여러번 읽게 된 것 같아서 수정 방향 한번 제안해 봅니다!!

2021-09-18 07:09 UTC, GwangYeol-Im commented on src/content/post/2021-09-10-ssr.md
> +프론트 서버로 사용자는 refresh token, access token 그리고 유저 정보를 보내고 프론트 서버는 이를 받아 세션에 저장한 후 세션 id를 사용자에게 돌려준다. 사용자는 이 세션 id를 만료 기간 전까지 쿠키로 가지고 있게 되고, 다음 웹페이지 접근 시 사용하게 된다.
```suggestion
사용자는 프론트 서버로 refresh token, access token 그리고 유저 정보를 보내고 프론트 서버는 이를 받아 세션에 저장한 후 세션 id를 사용자에게 돌려준다. 사용자는 이 세션 id를 만료 기간 전까지 쿠키로 가지고 있게 되고, 다음 웹페이지 접근 시 사용하게 된다.
```
로그인 로그아웃 과정을 이렇게 풀어주니 명쾌하네요! 덕분에 배워갑니다 :) 문장 관계만 살짝 수정 제안해봅니다! 그리고 브라우저, 사용자 중 하나의 단어를 일관되게 표현하는 건 어떨까요?

2021-09-18 07:09 UTC, GwangYeol-Im commented on src/content/post/2021-09-10-ssr.md
> +이번에는 로그인 상태에서 새로 고침을 통해 웹페이지 진입을 한다고 생각해보자. 일단 `로그인 상태`라는 것은 사용자가 세션 id를 쿠키로 가지고 있다는 의미와 같다. 그렇다면 쿠키 특성상 웹페이지 진입 시 자동으로 쿠키가 담겨 프론트 서버로 넘어가게 될 것이고 express에서는 세션 id를 통해서 사용자를 식별할 수 있다. 식별된 사용자의 정보에 따라
```suggestion
이번에는 로그인 상태에서 새로 고침을 통해 웹페이지 진입을 한다고 생각해보자. 일단 `로그인 상태`라는 것은 사용자가 세션 id를 쿠키로 가지고 있다는 의미와 같다. 그렇다면 쿠키 특성상 웹페이지 진입 시 자동으로 () 쿠키가 담겨 프론트 서버로 넘어가게 될 것이고 express에서는 세션 id를 통해서 사용자를 식별할 수 있다. 식별된 사용자의 정보에 따라 첫 html을 구성하고, access token도 사용자에게 넘겨 줄 수 있다.
```
`()` 부분에 쿠키가 어디에 담기는지 좀 더 명시적으로 설명해주면 좋을 것 같아요 ㅎㅎ

2021-09-18 07:09 UTC, GwangYeol-Im commented on src/content/post/2021-09-10-ssr.md
> +주의할 것은 이 방법이 XSS 공격에 취약할 수 있다는 사실이다. 하지만 간단한 해결법도 있으니 [여기](https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0)를 참고하여 XSS 공격을 방지할 수 있도록 하자.
`여기`에 대한 참조 링크가 유료 블로그라 참조가 쉽지는 않네요 ㅜㅜ.. 중요한 부분은 아니지만 짚고 넘어갈게요!

2021-09-19 11:16 UTC, 0307kwon commented on src/content/post/2021-09-10-ssr.md
> +사용자는 백엔드 서버로 로그인 요청을 보내고 access token과 refresh token을 받아올 것이다. access token은 브라우저에서 다음 사용자 권한이 필요한 요청에서 사용해야 하니 가지고 있어야 할 것이다. 문제는 누군가 내가 로그인한 상태를 기억하고 있어야 다음 웹페이지 접근 시 로그인 상태가 풀리지 않을 것이다. 이 역할을 프론트
오오 좀 더 매끄러운 문장이 된 것 같네요! 감사합니다~ 👍👍👍

2021-09-19 11:22 UTC, 0307kwon commented on src/content/post/2021-09-10-ssr.md
> +프론트 서버로 사용자는 refresh token, access token 그리고 유저 정보를 보내고 프론트 서버는 이를 받아 세션에 저장한 후 세션 id를 사용자에게 돌려준다. 사용자는 이 세션 id를 만료 기간 전까지 쿠키로 가지고 있게 되고, 다음 웹페이지 접근 시 사용하게 된다.
전부다 브라우저로 바꿔보려 했는데 관점과 상황에 따라 사용자가 적절한 경우가 조금 있더라구요! 그 부분을 제외하고 굳이 `사용자`라는 용어를 쓸 필요가 없는 곳은 모두 `브라우저`로 바꿔주었습니다~!

2021-09-19 11:47 UTC, 0307kwon commented on src/content/post/2021-09-10-ssr.md
> +주의할 것은 이 방법이 XSS 공격에 취약할 수 있다는 사실이다. 하지만 간단한 해결법도 있으니 [여기](https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0)를 참고하여 XSS 공격을 방지할 수 있도록 하자.
조금 수정해봤습니다! 

---

🎯 주의할 것은 이 방법이 XSS 공격에 취약할 수 있다는 사실이다. 하지만 간단한 해결법도 있으니 [여기](https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0)를 참고하여 XSS 공격을 방지할 수 있도록 하자. 요약하자면 script 태그에 정보를 담을 때 `JSON.stringify()`로 정보를 담아서는 안 되고 [serialize-javascript](https://github.com/yahoo/serialize-javascript)와 같은 라이브러리를 사용해서 담아야 한다는 것이다. 그 이유는 우리가 JSON.stringify()로 브라우저에 넘기는 정보가 악의적인 스크립트 태그를 가지고 있을 수도 있기 때문이다. 예를 들면 다음과 같다.

```html
<script>
  window.__userInJSON__ = {"username":"</script> <- 여기까지만 의도한 대로 실행 <script>alert(\"요건 몰랐지\")</script>"}
</script>
```

이 경우 유저네임에 악의적인 태그를 작성한 사용자에 의해 `alert("요건 몰랐지")` 메서드가 호출된다. 이 방법을 통해 민감한 작업을 수행한다면... 생각만 해도 아찔하다.

2021-09-19 11:55 UTC, 0307kwon commented
카일의 리뷰를 거치니까 글이 매끄러워졌어요!!! 완전 감사합니다 ㅋㅋㅋㅋㅋ

> 앱을 설계하는 초기 단계에서 적용해도 충분히 이점을 가져갈 수 있는 부분이라고 생각합니다.

그리고 이 부분에 대해서 생각을 해보았는데요. 저도 초기 단계에서도 충분히 적용할 수 있다고 생각합니다 ㅎㅎ
하지만 초기 단계에 앱을 빠르게 만들어 결과물을 봐야하는 상황에서 CSR의 장점이 크게 드러난다고 생각해서용 부담없이 시작할 수 있는 CSR로 시제품 제작을 많이 할 수도 있겠다, 라는 관점에서 글을 작성했습니다! 그래서 해당 부분은 남겨두도록 할게용 😊 의견 감사합니다!!!! 🧡

2021-09-20 09:28 UTC, 0imbean0 requested changes
리뷰가 늦어서 죄송합니다. 미키 😭
개인적으로 글이 사전 지식이 많이 필요로 해서 어려웠던 것 같아요.

글의 의도가 CSR 앱에서 SSR + CSR 환경으로 이주한 경험에 대한 공유라면
글의 머리 부분에 SSR과 refresh token에 대한 사전 지식이 필요하다는 부분을 언급해주면
지금도 괜찮다고 생각이 됩니다.

그게 아니라 SSR와 CSR 비교에 대한 부분과 refresh token에 대한 설명을 추가하는게 좋다면
글을 SSR와 CSR 비교와 SSR을 적용하면서 겪은 경험 두 개로 나누면 좋을 것 같아요.

> 🙋‍♂️ 로그인된 상태로 화면을 가져올 순 없을까?

이 부분을 기준으로 첫 글에는 SSR와 CSR 비교를 추가하고, 다음 글에는 refresh token에 대한 설명을 추가하면 글의 호흡도 길지 않고, 더 많은 사람이 읽기에 쉬운 글이 될 것 같아서 제안해봅니다.

2021-09-20 09:28 UTC, 0imbean0 commented on src/content/post/2021-09-10-ssr.md
> +![image](https://user-images.githubusercontent.com/48755175/133872438-a140deb8-6df0-4cf7-aafc-d947195fb8fe.png)
예시 그림의 설명이 맞는건지 궁금해요.
우선 그림에서 express 서버가 프론트 팀에서 다로 올린 html만 만들어주는 서버라고 생각되는데 맞나요?
제가 잘못 알고 있을 수 있는데, html과 같은 정적 리소스를 제공하는 서버는 WS로 정의하는게 맞는것 같아서요.

추가적으로 궁금한 부분은 첫 화면을 로드할 때는 
express 서버에서 백엔드 서버로 데이터를 요청해서 채운후 html을 만드는 건가요?

2021-09-20 11:27 UTC, 0307kwon commented on src/content/post/2021-09-10-ssr.md
> +![image](https://user-images.githubusercontent.com/48755175/133872438-a140deb8-6df0-4cf7-aafc-d947195fb8fe.png)
![image](https://user-images.githubusercontent.com/48755175/133872438-a140deb8-6df0-4cf7-aafc-d947195fb8fe.png)

우선 이 이미지가 맞을까용..? 사진 인용을 잘못하신 것이라고 생각하겠습니다 ㅋㅋㅋ

> 우선 그림에서 express 서버가 프론트 팀에서 따로 올린 서버(html만 만들어주는 서버)라고 생각되는데 맞나요?
제가 잘못 알고 있을 수 있는데, html과 같은 정적 리소스를 제공하는 서버는 WS로 정의하는게 맞는것 같아서요.

심바가 말씀하신대로 정적 리소스를 제공하는 서버는 WS가 맞습니다. 그런데 지금 저희가 제공하는 것은 html 내용이 동적으로 변경될 수 있는 동적 리소스기 때문에 (예를 들어 로그인 상태에 따라 달라진다던지...)  WAS에 더 가깝다고 할 수 있을 것 같습니다. 여기서 WS는 NginX 인데 reverse proxy의 역할로만 사용되고 있습니다. 저는 [얄코](https://www.youtube.com/watch?v=Zimhvf2B7Es&t=1s)의 도움을 많이 받았는데요. 강추드립니다. 설명 너무 잘해 증말

> 추가적으로 궁금한 부분은 첫 화면을 로드할 때는
express 서버에서 백엔드 서버로 데이터를 요청해서 채운후 html을 만드는 건가요?

현재 제가 예시로 상황에서는 백엔드 서버로 데이터를 보내고 있지는 않은데요. 백엔드 서버에 요청을 보내고 응답으로 html을 채운 뒤 브라우저에게 넘겨주는 것도 가능하다고 합니다. 곧 해볼 예정이지만 아직 해보지 않은 것이라 자신이 없어 글에 포함하지는 않았습니다 ㅋㅋㅋ [요기](https://react-query.tanstack.com/guides/ssr#on-the-server)를 보시면 리액트 쿼리로 미리 prefetch를 해서 html에 집어넣어주는 과정을 해주고 있어요. 제가 보기에는 가능해보입니다.

2021-09-20 11:56 UTC, 0307kwon commented
@0imbean0 심바 리뷰 감사합니다!!
심바의 의견을 듣고 제가 어떤 의도로 글을 쓴 것인지 다시 한번 고민해봤습니다!
그런데 제가 글을 쓴 의도는  CSR앱에 SSR을 적용하는데 어려움을 겪는 사람들을 위한 제 경험 전달에 더 가까운 것 같더라구용
그래서 글의 서두에 글의 의도와 사전 지식에 대한 언급을 추가해주었습니다

중요한 고민이었던 것 같습니다. 고마워요 심바!

2021-09-21 00:43 UTC, 0imbean0 commented on src/content/post/2021-09-10-ssr.md
> +![image](https://user-images.githubusercontent.com/48755175/133872438-a140deb8-6df0-4cf7-aafc-d947195fb8fe.png)
다른 이미지에 코멘트를 남겼군요. 그래도 찰떡같이 이해하고 답변해주셔서 감사합니다. 👍

2021-09-21 00:46 UTC, 0imbean0 approved these changes
수고하셨어요 미키.
SSR 공부해봐야지 생각만 하고있었는데, 덕분에 미뤄왔던 부채를 하나 줄일 수 있었습니다. 😀
Approve 하겠습니다.

2021-09-22 04:41 UTC, GwangYeol-Im approved these changes
리뷰가 많았음에도 불구하고 잘 수용해주어서 고마워요 미키!! 제 생각에도 글이 전반적으로 더욱 잘 읽히는 것 같아서 기분 좋네요 :) 저는 이만 Approve 남기도록 할게요~ 그리고 커밋 히스토리를 확인해보니 제 커밋과 같이 PR이 올라가 있는 거 같아서 이 부분 해결 후에 직접 머지해주시면 좋을 것 같습니다~!~!

2021-09-22 16:34 UTC, 0307kwon commented
@GwangYeol-Im 헐 잘못 올라가 있었군요!! 눈썰미 대박 👍👍
PR 이력 수정했고 머지하도록 하겠습니다!

2021-09-22 16:35 UTC, merged