[파피] 메시지 큐에 대해 알아보자
woowacourse/tecoble pull request #583
Opened 2021-09-20 01:45 UTC by TaewanKimmmm

## PR 체크 리스트
### 내용
- [x] 기술 용어를 통일했는가? - 영어, 한글 혼용 여부
- [x] 레퍼런스 형식을 통일했는가? - 레퍼런스는 글 마지막에 리스트 형식으로 작성
- [x] 글이 주제에 맞는 흐름으로 진행되었는가?
- [x] 태그가 올바르게 달려있는가?
- [x] 모든 리소스들에 대해 출처를 작성했는가?

### 스타일
- [x] 한 문장의 호흡이 너무 길지는 않은가?
- [x] 마크다운 문법과 맞춤법을 잘 준수하였는가?

<br/>

## 리뷰어에게 할 말

Kafka, RabbitMQ, ActiveMQ 등 메시지 큐 각각을 비교하는 내용도 쓰려고 했는데, 아직 제 깊이가 얕아 안 다루느니만 못할 것 같아 뺐습니다 ㅠㅠ 많은 피드백 부탁드립니다 감사합니다!!

<br/>

Close #566

2021-09-20 07:54 UTC, wannte requested changes
안녕하세요 파피! 몇가지 코멘트 남겼습니다! 확인 부탁드려요!

2021-09-20 07:54 UTC, wannte commented on src/content/post/2021-09-19-message-queue.md
> +- 어플리케이션과 데이터베이스 사이의 통신을 처리량에 따라 제어할 수 있다.
`웹 어플리케이션과 DB 사이에 커넥션에서 메세지 큐를 도입해야만 한다`의 장점들만 나열되어 있어서, DB를 연결해야 할 때, 항상 queue를 사용해야 한다는 결론을 내릴 수 있을 것 같아요.  물론 특정한 상황에서는 가능할 것 같은데, 그렇다면 그 특정 상황을 명시해 주어야 할 것 같아요.

DB Connection에 Queue를 사용하게 되었을 때, 다음과 같은 위험성들이 있을 것이라 생각이 들어요!
1. 데이터 베이스 장애 시, 어플리케이션이 정상 작동하는 게 옳은 것일까?
서비스의 대부분이 DB의 값을 수정하는 부분일 것인데, DB가 정상 작동하지 않았을 때, 어플리케이션이 동작한다는 부분이 모순적이다는 생각입니다.
2. 트랜잭션을 어떻게 관리할 것인가.
선착순 10개의 쿠폰이 있을 때, 1000명의 사용자가 동시에 요청을 보낸다고 했을 때, 모두 queue에 쌓이게 될 것인데, 어플리케이션에서는 이걸 모두 ok응답을 보내 주는 것이 좋은 서비스일까에 대해서 의문이 드네요.
3. 잘못된 요청에 대해서는 어떻게 처리할 것인가.
만약 잘못된 요청이 DB에 접근하게 되었을 때, 이걸 application에 어떻게 전달할 것인가. 또 그 application에서 client에게 요청이 잘못되었다고는 어떤 방식으로 전달할것인가 의문이 드네요


개인적으로는 DB 장애 관리의 해답으로 Queue의 도입에는 의문이 드네요.

오히려 요청 로그들을 관리를 하기 위해서 메시지 큐를 도입하는 부분에서 사용할 수 있을 것 같아요. MSA를 구축하는 데 있어서 매개체로 자주 쓰이는데, DB 커넥션 보다는 서비스 간의 데이터 흐름이르는 관점으로 보면 더 좋지 않을까라는 게 개인적인 생각입니다!

도입하려 했던 서비스는, 요청이 정상 처리 되었을 때, 사용자에게 이메일을 보내는 서비스 정도 생각이 드네요!

https://www.cloudamqp.com/blog/why-is-a-database-not-the-right-tool-for-a-queue-based-system.html 요런 자료도 있네요 참고해보면 좋을 것 같아요

너무 주장을 강하게 적은 것 같아 죄송... 합니당 ㅎㅎ

2021-09-20 07:54 UTC, wannte commented on src/content/post/2021-09-19-message-queue.md
> +실패한 작업에 대한 재실행이 가능하다.
Redundancy 와 `실패한 작업에 대한 재실행` 사이에 관계가 조금 연관성이 떨어진다? 라는 생각입니다!

2021-09-20 08:13 UTC, lns13301 approved these changes
안녕하세요 파피!
완태가 좋은 리뷰를 먼저해 줬네요.
저는 전체적인 문맥의 흐름이 자연스럽게 흘러가서 잘읽었습니다.
간단한 피드백 부분만 반영해 주시면 될 것 같아요.

2021-09-20 08:13 UTC, lns13301 commented on src/content/post/2021-09-19-message-queue.md
> +- 어플리케이션과 데이터베이스 사이의 통신을 처리량에 따라 제어할 수 있다.
저도 장점위주로 나열되어 있어서 메세지 큐의 위험성이나 단점과 관련된 주의사항이 포함되면 좋다고 생각합니다.

2021-10-04 06:14 UTC, wannte approved these changes
파피! 피드백 반영하느라 수고하셨습니다!!

메시지 큐를 사용할 수 있는 여러 예시를 들어줘서 이해에 도움이 되었던 것 같아요! 다소 무거운 피드백을 드렸지만, 파피의 방식에 맞게 잘 수정해주셨네요!

바로 어프루브 드리겠습니다!

2021-10-04 06:14 UTC, wannte commented on src/content/post/2021-09-19-message-queue.md
> +일반적인 클라이언트-서버 구조에서는 사용자가 요청을 하면 서버는 그에 대한 처리를 한 후 클라이언트에게 응답을 한다. 간단한 서버 구조에서는 굳이 메시지 큐를 사용할 필요가 없다. 사용자가 응답을 기다려야 하는 HTTP 요청을 바로 처리하지 않고 중간에 메시지 큐를 두는 경우는 썩 바람직하지 않아 보인다. 또한 메시지 큐를 적용하려면 다양한 메시지 큐 중
조금 더 명확하게 정보 전달할 수 있도록 수정되었네요!

2021-10-04 10:43 UTC, merged