[후디] - 이론과 실습을 통해 이해하는 Docker 기초
woowacourse/tecoble pull request #684
Opened 2022-09-25 10:32 UTC by devHudi

## PR 체크 리스트
### 내용
- [x] 기술 용어를 통일했는가? - 영어, 한글 혼용 여부
- [x] 레퍼런스 형식을 통일했는가? - 레퍼런스는 글 마지막에 리스트 형식으로 작성
- [x] 글이 주제에 맞는 흐름으로 진행되었는가?
- [x] 태그가 올바르게 달려있는가?
- [x] 모든 리소스들에 대해 출처를 작성했는가?

### 스타일
- [x] 한 문장의 호흡이 너무 길지는 않은가?
- [x] 마크다운 문법과 맞춤법을 잘 준수하였는가?

<br/>

## 리뷰어에게 할 말

이전에 블로그에 썼던 내용을 조금 다듬어서 올립니다! 리뷰 잘 부탁드립니다!

2022-09-26 09:06 UTC, tonic523 requested changes

2022-09-27 12:57 UTC, devHudi commented
@tonic523 리뷰 감사드립니다 토닉 👍 리뷰 전부 반영했어요 😄

2022-10-04 04:45 UTC, awesomeo184 requested changes

2022-10-04 04:45 UTC, awesomeo184 commented on src/content/post/2022-09-20-docker-basic.md
> +
```suggestion

도커는 **컨테이너 기반**의 오픈소스 가상화 플랫폼이다. 솔로몬 하익스가 개발했으며, 2013년에 처음 발표되었다. **고 (Go) 언어**로 개발되고 있다.

```
피동 표현을 능동형으로 수정해보았습니다.

2022-10-04 04:45 UTC, awesomeo184 commented on src/content/post/2022-09-20-docker-basic.md
> +
```suggestion
우리가 새로운 서비스를 개발하고 있는 개발자라고 생각해보자. 우리가 런칭하려는 서비스는 규모가 상당하여, 시스템 환경 설정부터, 방화벽, 네트워크 등의 **많은 설정이 필요**하다. 또한 Java, Python, Node.js 등 **많은 프로그래밍 언어**를 사용하고, 각각의 언어는 또 **많은 라이브러리 의존성**을 갖는다. 여기서 끝이 아니다. PostgreSQL, MariaDB, Redis 등 **여러개의 DBMS** 도 사용한다. 하지만, 우리는 유능한 개발자다. 이 많은 것들을 우리의 로컬 개발환경에 완벽하게 셋업했다.

```

이게 더 알맞지 않을까요?

2022-10-04 07:13 UTC, devHudi commented on src/content/post/2022-09-20-docker-basic.md
> +
반영하였습니다 👍

2022-10-04 07:13 UTC, devHudi commented on src/content/post/2022-09-20-docker-basic.md
> +
흐름상 이 표현이 더 자연스럽네요 👍

2022-10-04 11:11 UTC, merged