[센트] 마커 렌더링 최적화 초안 작성
woowacourse/tecoble pull request #792
Opened 2023-10-11 10:04 UTC by guridaek

## PR 체크 리스트
### 내용
- [ ] 기술 용어를 통일했는가? - 영어, 한글 혼용 여부
- [ ] 레퍼런스 형식을 통일했는가? - 레퍼런스는 글 마지막에 리스트 형식으로 작성
- [ ] 글이 주제에 맞는 흐름으로 진행되었는가?
- [ ] 태그가 올바르게 달려있는가?
- [ ] 모든 리소스들에 대해 출처를 작성했는가?

### 스타일
- [ ] 한 문장의 호흡이 너무 길지는 않은가?
- [ ] 마크다운 문법과 맞춤법을 잘 준수하였는가?

<br/>

## 리뷰어에게 할 말

잘 부탁 드립니다.

<br/>

2023-10-14 07:02 UTC, hgo641 reviewed
가람, 센트 글 작성하시느라 고생하셨습니다! 👍👍
설명이 잘 되어있어서 이해하기 쉬웠어요!
 코멘트 몇 개 남겨뒀으니 보시고 편하게 반영해주세요 🙇‍♀️

2023-10-14 07:02 UTC, hgo641 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +https://github.com/woowacourse-teams/2023-car-ffeine/pull/737
여기 헤더로 분리 안하고 윗 문장 바로 뒤에 
"... 문제를 구조 수정으로 인해 적용할 수 있게 되었다. ([작업한 PR링크](https://github.com/woowacourse-teams/2023-car-ffeine/pull/737))"

이렇게 간단하게 붙여도 될 것 같은데 어떤가요? 중요한 부분은 아니라서 편하게 반영해주세용

2023-10-16 04:00 UTC, xxeol2 reviewed
안녕하세요 센트!
테코블에 좋은 글 기고해주셔서 감사합니다!!
글의 depth를 한 번 확인해주시면 좋을 것 같아요
아래는 현재 글의 depth입니다~
```
- 마커 렌더링 최적화
--- 1. 개요
--- 2. 문제 원인 분석
--- 3. 문제 해결
--- 작업한 PR
-- 결과 분석
--- before
--- after
--- 개선 결과
```

2023-10-16 04:00 UTC, xxeol2 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +1 ~ 3 과정에서는 성능에 크게 영향을 끼칠 요소가 없지만 4번 과정은 일반적인 리액트 프로젝트를 개발할 때 겪는 과정이 아니다. 따라서 createRoot를 통해 많은 개수의 루트를 생성했을 때의 영향에 대해 알아보았다.
```suggestion
1 ~ 3번 과정에서는 성능에 크게 영향을 끼칠 요소가 없지만, 4번 과정은 일반적인 리액트 프로젝트를 개발할 때 겪는 과정이 아니다. 따라서 createRoot를 통해 많은 개수의 루트를 생성했을 때의 영향에 대해 알아보았다.
```
이런식은 어떤가요!

2023-10-16 04:00 UTC, xxeol2 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +리액트 공식 문서를 보니 페이지의 일부에 리액트를 뿌려서 사용하는 경우에는 루트를 필요한 만큼 생성해도 된다는 이야기가 포함되어 있었다. 따라서 4번 과정 또한 문제의 원인이라고 볼 수 없었다.
해당 공식 문서의 링크도 함께 첨부하면 좋을 것 같아요!
그리고 사진 형식 말고 인용 형식으로 적어줘도 괜찮을 것 같네용

2023-10-16 04:00 UTC, xxeol2 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +> 따라서 마커는 리액트 루트의 render 메서드를 호출해 리액트 컴포넌트를 렌더링하는 것으로 결정했다.
이 부분은 왜 인용절로 되어있나요 ?!

2023-10-19 15:26 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +카페인 서비스의 기존 마커 컴포넌트 구조에서는 마커 하나를 렌더링하기 위해 다음과 같은 과정을 거쳤다.
오 좋습니다! 추가로 왜 마커 렌더링을 최적화 목표로 잡았는지까지 적으면 좋을 것 같아서 추가해봤습니다!

2023-10-19 15:29 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +https://github.com/woowacourse-teams/2023-car-ffeine/pull/737
오 이게 훨씬 깔끔해보이네요! 반영 완료했습니닷

2023-10-19 15:32 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +> 하지만 6번 과정에서 리액트 컴포넌트를 직접 그리는 것이 아니라 구글 지도 api의 기본 마커를 사용하면 성능을 향상시킬 수 있지 않냐고 반문할 수도 있을 것이다. 이전에는 이러한 방식을 사용해 마커를 렌더링 했었다. 우리의 서비스는 현재 사용 가능한 충전소 개수를 마커를 통해서도 전달하기 때문에 이를 고려해 기본 마커를 사용할 때 다음의 두 가지 문
오 이거 한번 다 써봤는데 조금 복잡한 느낌이 들어서 그대로 두기로 했습니다 ㅠㅠ

2023-10-19 15:33 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +<img width="600" src="../images/2023-10-11-scent-3.png" />
반영 완료했습니다!! 이게 노션으로 적은걸 옮기다보니 사진이 작아진지 확인을 못했네요!

2023-10-19 15:35 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +1 ~ 3 과정에서는 성능에 크게 영향을 끼칠 요소가 없지만 4번 과정은 일반적인 리액트 프로젝트를 개발할 때 겪는 과정이 아니다. 따라서 createRoot를 통해 많은 개수의 루트를 생성했을 때의 영향에 대해 알아보았다.
오 이게 더 좋은 것 같네요! 반영 완료했습니다!!

2023-10-19 15:38 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +리액트 공식 문서를 보니 페이지의 일부에 리액트를 뿌려서 사용하는 경우에는 루트를 필요한 만큼 생성해도 된다는 이야기가 포함되어 있었다. 따라서 4번 과정 또한 문제의 원인이라고 볼 수 없었다.
반영 완료했습니다!! 👍

2023-10-19 15:38 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +> 따라서 마커는 리액트 루트의 render 메서드를 호출해 리액트 컴포넌트를 렌더링하는 것으로 결정했다.
오 이거 노션으로 저만 볼려고 적었던 글이라 형식이 제멋대로여서 생긴 이슈입니다... ㅋㅋㅋㅋㅋ 인용절로 돼있는 부분 풀어뒀습니다!

2023-10-21 11:53 UTC, Leejin-Yang reviewed
안녕하세요 센트! 좋은 글 올려주어서 감사해요 👍
카페인 렌더링 개선기..대단합니다 👍👍👍 전체적으로 쉽고 재밌게 읽을 수 있었어요
몇개 코멘트 남겼는데 확인해주세요~

2023-10-21 11:53 UTC, Leejin-Yang commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +이 `performWorkUntilDeadline` 라는 함수를 조금 알아보니 해당 함수는 간단히 말해 리액트에서 state의 변경이 한번에 많이 발생할 때 5ms의 데드라인 시간을 줄 때 사용하는 함수라는 것을 알게 되었다.
```suggestion
이 `performWorkUntilDeadline` 를 조금 알아보니 리액트에서 state의 변경이 한번에 많이 발생하는 경우 5ms의 데드라인 시간을 줄 때 사용하는 함수라는 것을 알게 되었다.
```

함수라는 말의 반복을 줄이고,' -때, -때'를 수정해보았는데 어떤가요??

2023-10-30 04:50 UTC, xxeol2 approved these changes

2023-10-31 01:27 UTC, Leejin-Yang approved these changes
고생했습니다!

2023-11-01 06:37 UTC, hgo641 approved these changes

2023-11-01 13:01 UTC, woowahan-cron requested changes
👋 안녕하세요 센트! 

레벨1~2 과정을 거쳐 리뷰어를 만나보긴 했지만, 이렇게 블로그 원고를 리뷰 받는 것은 처음이시죠?
프론트엔드 과정에서 만나뵌 것도 반가웠는데 이렇게 테코블에서 마주치게 되어 반가움은 2배가 되었습니다😆

센트가 기여했던 카페인 서비스를 개발하면서 겪었던 성능 이슈에 대해 어떤 고민을 했고 어떻게 해결해 보려고 했는지 문제를 접근하는 방식에서 센트의 많은 고민과 노력을 엿볼 수 있었어요!

그런데 몇 가지 다듬어야 하는 부분이 있어서 제가 제안해 드립니다.
정리하자면 다음과 같습니다.

## 1. 맞춤법 / 띄어쓰기 / 어색한 문장 고치기

- 맞춤법 검사기를 꼭 다시 돌려 주세요. 제가 눈으로 보니 맞춤법이 전혀 지켜지지 않은 부분이 상당히 있어서 곤란했습니다ㅠ
- 띄어쓰기의 경우에도 맞춤법 검사기를 돌리면 해결되는 부분이니 다시 돌려 주세요! 간혹 맞춤법 검사기가 띄어쓰기는 제대로 교정해 주지 못하는 경우가 있는데 그 부분은 제가 눈 린트로 피드백을 드릴 테니 걱정하지 않으셔도 됩니다! (한번 vs 한^번)
- 어색한 문장이 굉장히 많았어요. 센트가 영어를 많이 구사하신 것 같더라고요. 글을 읽을 때 번역된 문장을 읽는 느낌이 들어서 몰입하기가 어려운 점이 있었습니다ㅠ 이 부분은 글을 기고하기까지 주선해 주신 가람이나 다른 크루들의 도움을 받으면서 번역 투의 문장을 자연스럽게 고쳐보면 좋겠어요.

## 2. [지식의 저주](https://ko.wikipedia.org/wiki/%EC%A7%80%EC%8B%9D%EC%9D%98_%EC%A0%80%EC%A3%BC) 고려하기

- 사용자가 '카페인'이라는 서비스 이름을 들었을 때 대부분은 '카페' 또는 '커피'를 떠올릴 것 같아요. 그래서 처음에는 카페인이라는 서비스가 무엇인지와 함께 동음이의어이지만, 영문 철자를 기입해서 오해를 막는 것이 중요할 것 같아요. 
- 마커에 대한 렌더링 문제를 해결하기 위한 과정을 글로 푸는 것이지, 이곳에서 코드 리뷰를 하는 것은 아니기 때문에 과도하게 소스 코드와 관련된 것을 들고 오는 것은 저도 반대입니다. 하지만, 독자들이 맥락을 충분히 이해할 수 있도록 도식화한 보조 자료를 제시하거나, 이해를 돕기 위한 일부 코드나 아키텍처를 보여주는 것은 괜찮다고 봐요. 지금 독자들이 글을 읽었을 때는 어려운 부분이 있어요. 그부분은 제가 콕 짚어드렸으니 해당 피드백을 참고해 주세요!

## 3. 결론 추가하기

- 결론 부분을 추가해 주시면 글의 완성도가 올라갈 것 같아요 ㅎㅎ 이 부분도 고려해 주세요.

그 밖에도 짚어 드린 부분을 고민하시면서 글을 전반적으로 개선해 나가는 경험을 하시면 좋을 것 같습니다! 
고생하셨어요~ 다음 리뷰에서 뵙겠습니다!

2023-11-17 11:49 UTC, woowahan-cron requested changes
드디어 향기로운(Scent) 센트의 글이 세상 밖으로 나갈 시간이 다가오는 것 같아요😆

산발적으로 렌더링되는 현상에 대해 고민을 느끼고 그것을 어떻게 해결하면 좋을지 글을 통해 풀어 보니 확실히 정리가 잘된 느낌이네요!

다만, 제가 좀 더 리뷰를 드리고 싶었으나 다소 촉박한 일정으로 인해 양해를 부탁드리게 되었습니다. 

1. 이 글이 세상 밖을 보기 전에 다소 어색한 표현들에 관해 제안을 드렸어요! 검토하시고 수정 부탁드립니다.
2. 이미지가 너무 고퀄인데.. 센트가 만드신 것 같지만 그래도 물어봐야 할 것 같아서요. 직접 만드셨을까요? 만약에 퍼온 그림이라면 출처 표기를 부탁드리겠습니다! 또한, 외부 인용 금지된 옵션이 있는지도 확인 부탁드릴게요!


고생하셨어요~

2023-11-17 11:49 UTC, woowahan-cron commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +        list.map((item) => < key={item.id} item={item}>)
```suggestion
        list.map((item) => <Something key={item.id} item={item} />)
```

혹시 맞는지 확인 부탁드려요 뭔가 빠진 것 같아서요!
의도하셨거나 제가 틀렸다면 넘어가셔도 좋아요!

2023-11-17 11:49 UTC, woowahan-cron commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +일단 지난 마커 렌더링 최적화 이전 시점의 커밋으로 브렌치를 돌린 후 기존에 문제라고 생각했던 상태 변경을 일으키지 않으면서 전역 상태로 관리되는 마커 인스턴스 배열을 변화시키는 방법을 적용해 봤습니다. `(이 방법은 글 가장 하단부에 소개하도록 하겠습니다.)`
```suggestion
일단 지난 마커 렌더링 최적화 이전 시점의 커밋으로 브랜치를 돌린 후 기존에 문제라고 생각했던 상태 변경을 일으키지 않으면서 전역 상태로 관리되는 마커 인스턴스 배열을 변화시키는 방법을 적용해 봤습니다. `(이 방법은 글 가장 하단부에 소개하도록 하겠습니다.)`
```

외래어 표기법으로 "브랜치"가 맞습니다.

<img width="612" alt="image" src="https://github.com/woowacourse/tecoble/assets/112997662/86a476c4-3a0c-4e6c-a572-88cae992cb15">

2023-11-18 06:35 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +저희 서비스의 출발점은 `전기차 충전의 불편함`이었습니다. 최근 들어 보조금과 저렴한 유지비용 등의 이유로 전기차의 수요는 점점 증가하고 있지만, 그에 맞게 인프라가 함께 성장하고 있지 못하고 있습니다. 특히 충전에 관련된 불편함이 많이 대두되고 있습니다. 저희 서비스는 충전소 이용량 통계 정보를 제공함으로써 전기차 차주분들이 자발적으로 충전소를 분산 이
리뷰해주신 내용 적용 완료했습니다!

1. `최근 들어 보조금과 저렴한 유지비용 등의 이유로 전기차의 수요는 점점 증가하고 있습니다. 하지만, 인프라는 그에 맞게 충분히 성장하지 못했습니다.`로 문장을 수정했습니다.
2. `서비스의 주요 기능은 전국 6만개의 충전소와 그 내부 24만개의 충전기 정보 실시간 제공, 각 충전소 사용량 통계 정보 제공, 충전소 정보 불일치 신고 등이 있습니다.`로 문장을 수정했습니다.

2023-11-18 06:43 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +저희는 이러한 기능을, 지도를 기반으로 전달하고자 했습니다. 각 충전소의 위치를 지도상의 마커로 표현하고, 마커를 클릭할 시 해당하는 충전소의 세부 정보 및 사용량 통계를 볼 수 있도록 구성했습니다. 따라서 저희 서비스를 이용하는 사용자들이 가장 처음으로 접하는 중요 정보는 `마커`라고 할 수 있습니다. 서비스의 첫인상을 결정할 수 있는 마커의 렌더링이
제안해주신 내용 참고해서 문장을 다음과 같이 수정해봤습니다!!

`프로젝트 초반에는 이렇게 중요한 마커가 산발적으로 렌더링되는 문제가 있었습니다. 저는 이를 개선하고자 했습니다.`

2023-11-18 06:45 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +이제 제가 어떻게 산발적 마커 렌더링을 개선했는지 알아보도록 하겠습니다.
제안해주신 내용 반영했습니다!! 👍

2023-11-18 06:47 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +        list.map((item) => < key={item.id} item={item}>)
오오 제가 까먹고 이름을 안채웠나보네요 ㅠㅠ 수정 완료했습니다!

```js
function List() {
  return (
    <>
      {
        list.map((item) => <Item key={item.id} item={item} />)
      }
    </ㅣ>
  )
}
```

2023-11-18 06:49 UTC, kyw0716 commented on src/content/post/2023-10-11-marker-rendering-optimization.md
> +일단 지난 마커 렌더링 최적화 이전 시점의 커밋으로 브렌치를 돌린 후 기존에 문제라고 생각했던 상태 변경을 일으키지 않으면서 전역 상태로 관리되는 마커 인스턴스 배열을 변화시키는 방법을 적용해 봤습니다. `(이 방법은 글 가장 하단부에 소개하도록 하겠습니다.)`
꼼꼼한 리뷰 감사드립니다! 예전부터 저렇게 썼었는데 브랜치가 맞는 표현이었군요 ㅠㅠ ㅋㅋㅋㅋㅋㅋ

2023-11-18 06:54 UTC, kyw0716 commented
크론!! 우아콘 발표에 프리코스 마무리까지 정말 바쁘실텐데 시간 내어 꼼꼼한 리뷰 해주셔서 감사드립니다 👍👍
우테코 마지막 활동으로 크론에게 리뷰를 받을 수 있어 정말 영광이었습니다 ㅠㅠ (글이 한번 엎어져서 지난번 정성스러운 리뷰 내용들을 많이 반영하지 못한 것 같아 죄송해요 🥲)

우려하셨던 이미지 관련 내용은 전부 제가 만든 것이라 괜찮다고 말씀 드릴 수 있을 것 같습니다!! (이미지 퀄이 높다니 정말 영광입니다 하핫)

2023-11-20 08:19 UTC, woowahan-cron approved these changes
리뷰할 수 있는 기간이 짧아서 정말 필요한 부분만 확인한 점 양해해 주셔서 감사합니다🙏
그렇지만, 센트의 글에서는 무엇을 고민하고 어떤점을 고민했는지가 잘 드러나서 기간이 길어졌다고 하더라도 제가 리뷰해 드릴 수 있는 포인트가 더 있었을까? 하는 의문은 드네요 ㅎㅎ

아마도 프론트엔드 테코블 마지막 포스팅이 될 텐데 정말 수고 많으셨어요!
감사합니다!!!
꽃길만 걸어주세요 Scent!

2023-11-21 01:39 UTC, merged