[여우] 데이터베이스 복제하기(리플리케이션) - 2
woowacourse/tecoble pull request #808
Opened 2023-11-06 05:05 UTC by the9kim

## PR 체크 리스트
### 내용
- [x] 기술 용어를 통일했는가? - 영어, 한글 혼용 여부
- [x] 레퍼런스 형식을 통일했는가? - 레퍼런스는 글 마지막에 리스트 형식으로 작성
- [x] 글이 주제에 맞는 흐름으로 진행되었는가?
- [x] 태그가 올바르게 달려있는가?
- [x] 모든 리소스들에 대해 출처를 작성했는가?

### 스타일
- [x] 한 문장의 호흡이 너무 길지는 않은가?
- [x] 마크다운 문법과 맞춤법을 잘 준수하였는가?

<br/>

## 리뷰어에게 할 말
학습 고도화 팀이 프롤로그에서 선정한 우수 컨텐츠를 바탕으로 제작한 컨텐츠 입니다.

백엔드 크루 여우가 DB Replication을 주제로 작성했습니다.

분량이 긴 관계로 두 편으로 나눠서 포스팅할 예정입니다.

해당 PR은 두번 째 포스팅입니다.

<br/>

Close #{이슈_번호}

2023-11-08 12:19 UTC, poi1649 approved these changes
앞의 pr에서 말한 것 처럼 딱히 피드백을 드릴 내용은 없었습니다.
글에 엄청난 정성이 들어간 게 느껴지네요..
다만 걱정되는건 사진과 글이 혼재된 지금의 글의 테코블에 올라갔을 때, 이미지 크기나 형식에 맞게 보기 좋게 업로드 될 수 있을지 모르겠어요! 한 번 빌드를 미리 해보셔도 좋을 것 같습니다. 고생많으셨습니다.

2023-11-08 12:19 UTC, poi1649 commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +![](https://i.imgur.com/iK3m8Jb.png)
<img width="246" alt="image" src="https://github.com/woowacourse/tecoble/assets/74969077/401e5668-9190-4fe2-9910-89b5da7f70c3">
피드백은 아니고 Mixed 포맷이 왜 고래인지 궁금합니다ㅋㅋㅋ

2023-11-12 17:01 UTC, aiaiaiai1 approved these changes
안녕하세요 여우~ 글 잘 읽었어요!
긴글임에도 불구하고 테코의 이야기와 재치있는 사진 덕분에 긴줄 모르고 읽었습니다!
글 작성하시느라 고생 많으셨습니다~! 👏 👏 👏

2023-11-16 08:46 UTC, the9kim commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +![](https://i.imgur.com/HTRCFAc.png)
`~ 데이터베이스 변경 내용을 각각의 SQL 문장(statement) 단위로 로그에 기록한다고 하여~`

영어 표기의 첫글자는 대문자로 통일(위의 경우 statement)해도 좋을 듯 합니다.

2023-11-16 08:46 UTC, the9kim commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +
`~ 실행할 때마다 같은 결과를 낸다는 보장을 할 수 없는 쿼리 ~`

-없는 이라는 단어에 `밑줄`이 쳐져 있는데요. 의도하신 게 아니라면 제거해도 좋을 듯 합니다.

2023-11-16 08:46 UTC, the9kim commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +데이터를 동일하고 안전하게 복제하면서도 바이너리 로그의 크기를 적당하게 유지할 수 있는 좋은 방법은 없을 걸까요 🥹
```suggestion
데이터를 동일하고 안전하게 복제하면서도 바이너리 로그의 크기를 적당하게 유지할 수 있는 좋은 방법은 없을까요 🥹
```
```suggestion
데이터를 동일하고 안전하게 복제하면서도 바이너리 로그의 크기를 적당하게 유지할 수 있는 좋은 방법은 없는 걸까요 🥹
```

2023-11-16 08:46 UTC, the9kim commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +이름에서 유추할 수 있듯, 소스 서버의 이벤트가 리플리카 서버들에게 잘 전송되었는지 확인하지 **않기** 때문에
```suggestion
이름에서 유추할 수 있듯, 소스 서버의 이벤트가 리플리카 서버들에게 잘 전송되었는지 확인하지 않기 때문에
```
`않기`에 들어간 볼드는 의도하신 것일까요? 아니라면 삭제해도 좋을 듯 합니다!

2023-11-16 08:54 UTC, the9kim commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +동기면 그냥 동기 하지 왜 **반**만 동기일까요?
```suggestion
동기면 그냥 동기지 왜 **반**만 동기일까요?
```

`동기 하지 `라는 표현이 조금 모호한 듯 한데요. 의도하신 것이 아니라면 고쳐봐도 좋을 듯 합니다!

2023-11-17 01:07 UTC, BackFoxx commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +![](https://i.imgur.com/iK3m8Jb.png)
MYSQL 아이콘이 고래라서 ㅋㅋㅌㅌㅋㅋㅋ

2023-11-17 05:32 UTC, zillionme requested changes
안녕하세요 여우!
1편에 이어서 2편도 잘 읽었습니다. 리플리케이션에 대해 잘 몰랐는데, 긴 글임에도 이해가 쉽게 잘 풀어내신 것 같아요👍🏻👍🏻👍🏻
사소한 리뷰를 달아보았는데, 고려하셔서 적용하시면 될 것 같습니다.

2023-11-17 05:32 UTC, zillionme commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +![](https://i.imgur.com/q318cWl.png)
소스 서버가 트랜잭션을 커밋한 후, 리플리카 서버에 이벤트를 전송하는 도중 장애가 발생하면,
소스 서버의 데이터와 레플리카 서버의 데이터 정합성에 문제가 생기는 건가요?

2023-11-17 06:47 UTC, zillionme approved these changes

2023-11-17 07:51 UTC, BackFoxx commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +테코네 카페의 데이터베이스 리플리케이션은 **비동기 복제(Asynchronous replication)** 방식으로 동작하고 있었기 때문인데요!
'일정 시간 지연 후에 데이터를 복제하는 방식' 이라는 문장이 정확한 사실인지 파악하는 시간이 오래 걸릴 수 있어, 지금은 반영하지 않을게요!

2023-11-17 07:51 UTC, BackFoxx commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +![](https://i.imgur.com/UwQbvoE.png)
네! 개발자가 수동으로 확인해야 합니다

2023-11-17 07:52 UTC, BackFoxx commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +![](https://i.imgur.com/q318cWl.png)
그렇습니다!

2023-11-17 12:41 UTC, woowahan-cron requested changes
여우! 이번 편의 글도 매끄럽게 잘 써주셨어요!

2023년 11월 24일이 수료인 만큼 저의 리뷰 시점과 여우의 검토, 그리고 저의 최종 리뷰 시점 모두 20일 월요일에는 완료되어야 안정적으로 수료 전에 테코블에 배포가 될 것이라고 생각했어요.
그래서 내용에 대해서는 자세한 피드백을 드리지 못한 점 양해 부탁드리고요!
대체로 맞춤법도 잘 지켜주셨고 제가 리뷰할 만한 포인트가 많지는 않은 것 같아요.

그렇지만, 그림과 관련된 리뷰를 드리자면요!

- flaticon의 아이콘을 가져왔다고 들었는데요. [무료 버전의 경우 저작권을 표기해야 한다](https://support.flaticon.com/s/article/Attribution-How-when-and-where-FI?language=en_US)고 홈페이지에 나와 있어요. 앞선 PR의 리뷰와 동일하게 저작권 표기가 들어갔으면 좋겠습니다ㅠ

고생하셨습니다!

2023-11-17 12:41 UTC, woowahan-cron commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +title: '테코와 알아보는 대규모 데이터 관리 - 데이터베이스 복제하기(리플리케이션)'
[이전 PR의 리뷰 포인트](https://github.com/woowacourse/tecoble/pull/807/files#r1397201529)와 동일합니다!

그리고 1과 2에서 다루는 내용에 대한 차이점이 있을 것 같은데 1편은 1편대로, 2편은 2편대로 어떤 내용을 다루는지에 대한 키워드를 뽑아서 적어주는 것도 좋을 것 같아요!

2023-11-17 12:41 UTC, woowahan-cron commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +오히려 반동제 복제를 사용했을 때 데이터베이스의 작업 처리 속도가 느려져서 불편해할 사람들이 더 많겠구나! 라는 결론을 내렸어요.
```suggestion
오히려 반동기 복제를 사용했을 때 데이터베이스의 작업 처리 속도가 느려져서 불편해할 사람들이 더 많겠구나! 라는 결론을 내렸어요.
```

맞을까용?

2023-11-17 12:41 UTC, woowahan-cron commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +BackFoxx marked this conversation as resolved.
백여우 블로그의 이미지를 가져온 것 같군요 ㅋㅋ
제가 지금 내용 리뷰는 안 하고 있는데요!
`BackFoxx marked this conversation as resolved.`을 넣으신 의미가 무엇인가요?
해당 이미지 속 내용과 연관이 있을까요?

2023-11-17 12:41 UTC, woowahan-cron commented on src/content/post/2023-11-06-zero-downtime-deployment-2.md
> +  Real MySQL 8.0 2권 494p ~ 503p
```suggestion
  Real MySQL 8.0 2권 p.494~503
```

```suggestion
  Real MySQL 8.0 2권 pp.494-503
```

2023-11-20 12:27 UTC, woowahan-cron approved these changes
이렇게 2편까지 한 번에 작업하시는 게 힘드셨을 텐데 끝까지 진행해 주셔서 감사드릴 따름입니다!
또한, 저작권 문제로 인해 출처 표기를 요청 드렸는데 번거로운 작업을 빠른 시간 내에 처리해 주셔서 정말 감사드려요!

이제 수료식이 얼마 남지 않았잖아요!
수료식 직전에 이렇게 위대한 글이 테코블에 게재될 것을 상상하니
한편으로 1년간 브랜딩 근로 코치로 활동하면서 뿌듯한 순간이었던 것 같아요.

우아한테크코스에서 선한 영향력으로 다른 크루들에게 도움이 되고 이렇게 풍성한 글을 올려주셨던 것과 같이 사회에서도 더욱 좋은 영향력을 끼치는 사회인이 되시기를 기대하고 응원하겠습니다
이제 우아한테크코스는 6기와 🏃🏻‍♀️🏃🏼‍♂️ 바톤 터치!!

2023-11-23 04:34 UTC, merged